-- ============================================================================
-- INVOICES.DB — CANONICAL SCHEMA v2.1.3.0
-- Helium Core Service / Float SDK (sync.db invoices partition)
--
-- Date:    2026-03-26
-- Status:  Authoritative — supersedes Core v1.0 + SDK schema.py v1/v2
-- Author:  Aligned from Documentation/Schema/invoice/ session (2026-02-24 – 2026-02-26)
--
-- This file is the single source of truth for:
--   • Core:    Services/Core/schemas/sqlite/invoices_sqlite.sql
--   • SDK:     Float/App/SDK/src/ws1_database/schema.py  (INVOICES_TABLE)
--   • Core PG: Services/Core/schemas/postgres/invoices.sql
--
-- Key changes from v1.0 → v2.0 → v2.1:
--   (see git history for full changelog)
--
-- v2.1.0.1 changes (2026-02-26 — SIGNED OFF):
--   Version format: {helium_major}.{helium_minor}.{customer_major}.{customer_minor}
--     First two numbers (2.1) = Helium platform version.
--     After second period (.0.1) = customer-specific extensions.
--
--   • PARTY RENAME: tenant_*/customer_* → seller_*/buyer_* for audit clarity.
--     - seller = the invoicing party (OUTBOUND: tenant, INBOUND: counterparty)
--     - buyer  = the paying party   (OUTBOUND: counterparty, INBOUND: tenant)
--     - company_id remains as the tenant anchor regardless of direction.
--     - Frontend displays the counterparty as "Customer" in both cases.
--   • Added seller_id (tenant had no _id previously)
--   • ADDRESS SPLIT: seller_city / buyer_city added as separate fields.
--     seller_address / buyer_address = street only. FIRS requires city_name
--     as a separate mandatory field in postal_address.
--   • DATES: Added sign_date, transmission_date, acknowledgement_date.
--     Removed firs_submitted_at (replaced by transmission_date).
--   • IRN/QR OWNERSHIP CORRECTED: Both generated by HELIUM, not FIRS.
--   • NOTES: Dropped generic `notes`. Standardized to:
--     - notes_to_firs   → maps to FIRS `note` field (max 500 chars)
--     - payment_terms_note → maps to FIRS `payment_terms_note` (max 500 chars)
--   • SDK SYNC: Removed sync_version, remote_id, remote_synced_at from canonical
--     schema. These belong in the SDK's local sync.db replica only.
--   • SCHEMA TRACKING: Added schema_version_applied on invoices for audit.
--   • TAX CATEGORIES: Expanded enum from 6 to 25 values (24 FIRS API + NEPZA).
--   • TABLE COUNT: 8 tables (schema_version + 7 invoice tables), 171 fields total.
--   • IRN: Now NOT NULL — every invoice must have an IRN at creation (idempotency key).
--   • actor_service: Removed from invoice_transmission_attempts (TBD — retry initiation tracking).
--
-- v2.1.0.2 changes (2026-02-27):
--   Gap closure from FIRS payload round-trip audit (Transforma → Core → Edge → FIRS).
--   • WITHHOLDING_TAX: Added to invoice_tax_categories enum (25 → 26 values).
--     Aramex Transforma uses WITHHOLDING_TAX category in tax_total[].tax_subtotal[];
--     the v2.1 expansion dropped the old WITHHOLDING value without replacement.
--   • wht_amount: Denormalized WHT total on invoices table (display convenience —
--     avoids JOIN to invoice_tax_categories for SWDB "WHT ₦" column).
--   • discount_amount: Precise discount float on invoices (replaces boolean-only has_discount).
--   • adjustment_type: Credit/debit note classification (PRICE_ADJUSTMENT, FULL_CANCELLATION, etc.).
--   • invoice_allowance_charges: NEW TABLE — stores FIRS allowance_charge[] entries
--     for audit round-tripping. Both invoice-level and line-level allowances/charges.
--   • TABLE COUNT: 9 tables (schema_version + 8 invoice/support tables), 191 fields total.
--   • INVOICES TABLE: 115 fields (was 105).
--   • TABLE NUMBERS: 0–8 (0=schema_version, 1=invoices, 2=line_items, 3=references,
--     4=tax_categories, 5=attachments, 6=transmission_attempts, 7=allowance_charges, 8=history).
--
-- v2.1.2.0 changes (2026-03-21 — ReviewPage fields):
--   • product_summary: TEXT — computed "Item 1 (+N more)" for SWDB Product Description column
--   • line_items_count: INTEGER — count of line items per invoice
--   • foc_line_count: INTEGER — count of FOC (zero-price) line items
--   • document_source: TEXT — source file info ("workbook.xlsx / Sheet Name")
--   • other_taxes: REAL — combined WHT + levies (separate from VAT)
--   • custom_duties: REAL — optional customs duty amount
--   • INVOICES TABLE: 115 → 121 fields (+6 new)
--   • TABLE COUNT: 9 tables, 191 → 197 fields total (+6 new on invoices)
--
-- v2.1.3.0 changes (2026-03-26 — Field audit reconciliation):
--   Painstaking field-by-field audit against WS5 reconciliation doc.
--   • ADDED 9 invoice fields: finalize_trace_id, status_notes, payment_updated_at,
--     payment_updated_by, firs_submitted_payload, fixed_invoice_blob_uuid,
--     customer_total_invoices_at_commit, customer_lifetime_value_at_commit,
--     customer_compliance_score_at_commit
--   • REMOVED 1 invoice field: category (scrapped at invoice level — per-line-item only)
--   • ADDED 5 line_items fields: customer_sku, oem_sku, helium_sku, full_description, vat_rate
--   • ADDED tenant_invoice_metrics table (TABLE 9)
--   • PRO- prefix: helium_invoice_no format is PRO-{TenantID}-{invoice_id} (was WM-)
--   • INVOICES TABLE: 121 → 130 fields (+9 new, -1 removed, +1 = 130 incl id)
--   • LINE_ITEMS TABLE: 21 → 26 fields (+5 new)
--   • TABLE COUNT: 10 tables, 197 → 214 fields total
--
-- v2.1.1.0 changes (2026-03-01 — HELIUM_SECURITY_SPEC alignment):
--   • trace_id → invoice_trace_id (Core-generated, invoice-specific trace UUID v7)
--   • Added user_trace_id (SDK-generated UUID v7 from USER-TRACE block)
--   • Added x_trace_id (Relay-generated UUID v7, server authority trace)
--   • user_id → helium_user_id (HeartBeat-assigned, from JWT sub claim)
--   • Added machine_guid, mac_address, computer_name (composite machine fingerprint)
--   • Added float_id (HeartBeat-assigned Float instance), session_id (active session UUID)
--   • INVOICES TABLE: 108 → 115 fields (2 renames + 7 new)
--   • TABLE COUNT: 9 tables, 184 → 191 fields total (+7 new on invoices)
--   • Security Spec: HELIUM_SECURITY_SPEC.docx (2026-03-01) §3, §6
--
-- FIRS COMPLIANCE CONFIRMATION (v2.1.0.2):
--   • 26/26 mandatory signing fields:   COVERED (direct field mapping)
--   • 5/5  conditional B2B tx fields:    COVERED (direct field mapping)
--   • 31/31 full B2B transmission:       COVERED
--   • city_name: separate seller_city / buyer_city fields (no Edge parsing needed).
--
-- DIRECTION → PARTY ROLE MAP:
--   ┌──────────────────────────┬──────────────────┬───────────────────┐
--   │ direction                │ seller_* =       │ buyer_* =         │
--   ├──────────────────────────┼──────────────────┼───────────────────┤
--   │ OUTBOUND                 │ Tenant (us)      │ Counterparty      │
--   │ INBOUND                  │ Counterparty     │ Tenant (us)       │
--   │ SELF_BILLED_INVOICE      │ Counterparty     │ Tenant (us)       │
--   │ SELF_BILLED_CREDIT       │ Counterparty     │ Tenant (us)       │
--   └──────────────────────────┴──────────────────┴───────────────────┘
--
-- SDK SYNC NOTE (for sync team):
--   The SDK's local sync.db replica of the invoices table should add:
--     sync_version     INTEGER NOT NULL DEFAULT 0
--     remote_id        TEXT
--     remote_synced_at TEXT
--   These fields are NOT part of the canonical invoices.db schema.
--
-- UI NOTE — INBOUND STATUS DISPLAY:
--   For inbound invoices, the "Status" column in the SWDB (eInvoices tab) displays
--   inbound_status values (PENDING_REVIEW, ACCEPTED, REJECTED, EXPIRED) instead of
--   workflow_status values. The column renders as an authenticated dropdown that
--   elevated users can interact with to accept/reject. The acceptance/rejection
--   flows through: Float App → SDK → Core → Edge → FIRS.
-- ============================================================================


-- ============================================================================
-- TABLE 0: SCHEMA VERSION
-- Purpose: Tracks schema migrations. Audit: invoices.schema_version_applied
--          records which version was active when each invoice was created.
-- ============================================================================

CREATE TABLE IF NOT EXISTS schema_version (
    version     TEXT PRIMARY KEY,
    applied_at  TEXT DEFAULT (datetime('now')),
    description TEXT
);

INSERT INTO schema_version (version, description)
VALUES ('2.1.0.1', 'Seller/buyer party split, city_name separation, FIRS tax categories (25), date lifecycle fields, IRN/QR ownership fix, notes standardization');

INSERT INTO schema_version (version, description)
VALUES ('2.1.0.2', 'WHT tax category (26 values), allowance_charge table, wht_amount/discount_amount/adjustment_type columns');

INSERT INTO schema_version (version, description)
VALUES ('2.1.1.0', 'Security spec alignment: 3-level trace model, composite machine fingerprint, HeartBeat identity fields');

INSERT INTO schema_version (version, description)
VALUES ('2.1.2.0', 'ReviewPage fields: product_summary, line_items_count, foc_line_count, document_source, other_taxes, custom_duties');

INSERT INTO schema_version (version, description)
VALUES ('2.1.3.0', 'Field audit: +9 invoice (finalize_trace_id, status_notes, payment snapshots, FIRS payload), -1 (category removed), +5 line_items (SKU self-containment), +tenant_invoice_metrics table, PRO- prefix');


-- ============================================================================
-- TABLE 1: invoices (130 fields incl. id)
-- Owner:  Core (authoritative writer)
-- Reads:  Edge (transmission_status updates via contract), Float SDK (read-only)
-- ============================================================================

CREATE TABLE invoices (

    -- ── A. Primary identification (10 fields) ────────────────────────────────

    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Internal system identifier: 16-digit hex (e.g. A3F7B2C9D1E4F5A6).
    -- All internal API calls, logs, and cross-service references use this.
    invoice_id                  TEXT UNIQUE NOT NULL,

    -- Full display identifier: PRO-{TenantID}-{invoice_id}.
    -- Used in support contexts, UI labels, and FIRS cross-references.
    -- Immutable once committed. Generated by Core at COMMITTED transition.
    helium_invoice_no           TEXT UNIQUE NOT NULL,

    -- Business invoice number.
    -- OUTBOUND: client-generated (e.g. INV-2026-001, WN42752).
    -- INBOUND:  supplier's invoice number from the received document.
    -- This is the SWDB "Invoice No" column. Used to derive IRN.
    invoice_number              TEXT NOT NULL,

    -- Invoice Reference Number. Generated by HELIUM at commit/sign time.
    -- Format: INVOICE_NUMBER-SERVICE_ID-DATESTAMP (e.g. INV001-94ND90NR-20260215).
    -- Sent TO FIRS as part of the payload. FIRS validates it; they do NOT generate it.
    -- IDEMPOTENCY KEY: IRN serves as Helium's idempotency key. No two invoices
    -- share an IRN. FIRS uses it for deduplication. Every invoice MUST have an IRN
    -- at creation — there is no valid state without one.
    irn                         TEXT UNIQUE NOT NULL,

    -- Cryptographic Stamp Identifier. Generated by HELIUM at signing.
    -- NOT generated by FIRS.
    csid                        TEXT,
    -- PENDING | ISSUED | FAILED
    csid_status                 TEXT CHECK (csid_status IN ('PENDING', 'ISSUED', 'FAILED')),

    -- Core-generated UUID v7 — invoice-specific trace. Part of 3-level chain:
    -- user_trace_id (SDK) → x_trace_id (Relay) → invoice_trace_id (Core)
    invoice_trace_id            TEXT,

    -- SDK-generated UUID v7 from USER-TRACE block. Client origin trace.
    -- Generated on user gesture before any HTTP call. Propagated blob → invoice.
    user_trace_id               TEXT,

    -- Relay-generated UUID v7. Server authority trace.
    -- Generated after JWT validation. Propagates on all internal service calls.
    x_trace_id                  TEXT,

    -- SDK-generated UUID v7 at the finalize gesture time.
    -- Distinct from user_trace_id (upload time) — captures the commit action trace.
    finalize_trace_id           TEXT,

    -- Snapshot reference to the supplier/EIC config version active at commit time.
    -- Ensures reproducible re-processing if config changes post-submission.
    config_version_id           TEXT,

    -- Schema version in effect when this invoice was created. Immutable after insert.
    -- Links to schema_version.version for audit trail.
    schema_version_applied      TEXT,

    -- ── B. Three independent classifiers + FIRS type code (4 fields) ────────
    -- ALL required, ALL independent. Do NOT collapse.

    -- OUTBOUND = tenant is the seller (issuing the invoice).
    -- INBOUND  = tenant is the buyer (receiving the invoice).
    direction                   TEXT NOT NULL DEFAULT 'OUTBOUND'
                                    CHECK (direction IN ('OUTBOUND', 'INBOUND')),

    -- Document class. Independent of direction.
    document_type               TEXT NOT NULL DEFAULT 'COMMERCIAL_INVOICE'
                                    CHECK (document_type IN (
                                        'COMMERCIAL_INVOICE',
                                        'CREDIT_NOTE',
                                        'DEBIT_NOTE',
                                        'SELF_BILLED_INVOICE',
                                        'SELF_BILLED_CREDIT'
                                    )),

    -- FIRS invoice type code — raw numeric code sent in the FIRS payload.
    -- Stored alongside document_type for audit immutability.
    -- Mapping: COMMERCIAL_INVOICE→380, CREDIT_NOTE→381, DEBIT_NOTE→383,
    --          SELF_BILLED_INVOICE→389, SELF_BILLED_CREDIT→261.
    firs_invoice_type_code      TEXT,

    -- B2B | B2G | B2C — drives FIRS eligibility, tax rules, transmission path.
    transaction_type            TEXT NOT NULL DEFAULT 'B2B'
                                    CHECK (transaction_type IN ('B2B', 'B2G', 'B2C')),

    -- ── C. Dates (7 fields) ─────────────────────────────────────────────────

    -- Date on the invoice document (ISO date string: YYYY-MM-DD).
    issue_date                  TEXT NOT NULL,

    -- Optional time component of issue (HH:MM:SS).
    issue_time                  TEXT,

    -- Document-stated due date: what the invoice PDF/source document says.
    -- Higher authority — can trigger direct email alerts.
    -- SWDB column header: "Invoice Due Date"
    due_date                    TEXT,

    -- Platform-calculated payment due date: computed from issue_date + agreed credit terms.
    -- Used for internal SLA alerts only. May differ from due_date.
    -- SWDB column header: "Calculated Payment Due"
    payment_due_date            TEXT,

    -- When Helium signed the invoice (IRN + QR code generated). Pre-transmission.
    sign_date                   TEXT,

    -- When the invoice was actually sent to FIRS. Replaces old firs_submitted_at.
    transmission_date           TEXT,

    -- When the counterparty accepted the invoice.
    -- OUTBOUND: when the buyer acknowledged receipt/acceptance.
    -- INBOUND:  when this tenant accepted the supplier's invoice.
    acknowledgement_date        TEXT,

    -- ── D. Financial (7 fields) ─────────────────────────────────────────────

    -- Primary transaction currency (ISO 4217). Default NGN.
    document_currency_code      TEXT NOT NULL DEFAULT 'NGN',

    -- Tax computation currency. Usually same as document_currency_code.
    -- Separate field required for cross-currency B2B transactions.
    tax_currency_code           TEXT NOT NULL DEFAULT 'NGN',

    -- Pre-tax total. Maps to FIRS legal_monetary_total.line_extension_amount.
    -- tax_exclusive_amount = subtotal - allowances + charges (see invoice_allowance_charges).
    subtotal                    REAL NOT NULL DEFAULT 0.0,

    -- Total VAT/tax across all line items.
    tax_amount                  REAL NOT NULL DEFAULT 0.0,

    -- Grand total (subtotal + tax_amount).
    -- Maps to FIRS legal_monetary_total.tax_inclusive_amount AND payable_amount.
    total_amount                REAL NOT NULL DEFAULT 0.0,

    -- Exchange rate from document_currency_code to tax_currency_code.
    -- Required when the two currencies differ. NULL when same currency.
    exchange_rate               REAL,

    -- Whether this invoice has any discount/allowance entries (convenience flag).
    -- Detailed allowances stored in invoice_allowance_charges table.
    has_discount                INTEGER NOT NULL DEFAULT 0,

    -- Withholding tax amount (denormalized from invoice_tax_categories for display).
    -- NULL when no WHT applies. Maintained by application on commit/update.
    -- Allows SWDB "WHT ₦" column without JOIN to invoice_tax_categories.
    wht_amount                  REAL,

    -- Precise discount amount (denormalized from invoice_allowance_charges for display).
    -- NULL when no discount. has_discount is the boolean convenience; this is the value.
    discount_amount             REAL,

    -- Credit/debit note adjustment classification from Transforma/ingestion.
    -- Examples: PRICE_ADJUSTMENT, FULL_CANCELLATION, QUANTITY_CORRECTION, RETURN.
    -- NULL for standard commercial invoices.
    adjustment_type             TEXT,

    -- ── E. Payment means + FIRS code (2 fields) ─────────────────────────────
    -- How the buyer pays. Nullable (IBN — Include But Nullable).
    -- Human-readable; Edge maps to FIRS numeric codes at transmission
    -- (10=Cash, 20=Cheque, 30=Credit Transfer, 42=Payment to account, 8=Bank card).
    payment_means               TEXT CHECK (payment_means IS NULL OR payment_means IN (
                                    'CASH', 'CHEQUE', 'BANK_TRANSFER', 'CARD',
                                    'MOBILE_MONEY', 'DIGITAL_WALLET', 'OFFSET', 'OTHER'
                                )),

    -- FIRS payment means code — raw numeric code sent in the FIRS payload.
    -- Stored alongside payment_means for audit immutability.
    -- Mapping: CASH→10, CHEQUE→20, BANK_TRANSFER→30, CARD→48,
    --          MOBILE_MONEY→49, DIGITAL_WALLET→49, OFFSET→97, OTHER→1.
    firs_payment_means_code     TEXT,

    -- ── F. Delivery / fulfilment (2 fields) ─────────────────────────────────
    -- IBN fields — nullable, populated when applicable.

    delivery_date               TEXT,
    delivery_address            TEXT,

    -- ── G. Commercial references (2 fields) ─────────────────────────────────
    -- IBN fields — nullable, populated when applicable.

    -- Buyer's purchase order number. Critical for B2G transactions.
    purchase_order_number       TEXT,

    -- Contract/agreement number under which this invoice falls.
    contract_number             TEXT,

    -- ── H. Three-status model (4 fields) ────────────────────────────────────
    -- Three INDEPENDENT state machines. Do not conflate.

    -- High-level invoice lifecycle. Core is the ONLY authoritative writer.
    -- Users cannot update this field regardless of privilege.
    -- See: 02_WORKFLOW_STATUSES_V1.md for full state machine and transitions.
    workflow_status             TEXT NOT NULL DEFAULT 'COMMITTED'
                                    CHECK (workflow_status IN (
                                        'COMMITTED',
                                        'QUEUED',
                                        'TRANSMITTING',
                                        'TRANSMITTED',
                                        'VALIDATED',
                                        'ERROR',
                                        'ARCHIVED'
                                    )),

    -- Detailed outbound/inbound exchange progression.
    -- Core owns schema/domain. Edge writes through controlled contract.
    -- See: 03_TRANSMISSION_STATUSES_V1.md for full state machine.
    transmission_status         TEXT NOT NULL DEFAULT 'NOT_REQUIRED'
                                    CHECK (transmission_status IN (
                                        'NOT_REQUIRED',
                                        'PENDING_PRECHECK',
                                        'PRECHECK_PASSED',
                                        'BLOCKED_COUNTERPARTY',
                                        'SIGNING',
                                        'SIGNED',
                                        'TRANSMIT_PENDING',
                                        'TRANSMITTING',
                                        'TRANSMITTED',
                                        'ACCEPTED',
                                        'REJECTED',
                                        'FAILED_RETRYABLE',
                                        'FAILED_TERMINAL'
                                    )),

    -- Concise error summary for the most recent transmission failure.
    -- Cleared on successful retry. Full history in invoice_transmission_attempts.
    transmission_status_error   TEXT,

    -- Human-readable notes about current status. Set by Core when workflow/transmission
    -- transitions happen. Displayed in UI as contextual explanation (e.g. "Rejected by FIRS:
    -- invalid TIN", "Queued for retry", "Payment confirmed by buyer").
    status_notes                TEXT,

    -- Payment lifecycle. This is the ONLY status field users can update (permission-gated).
    -- OVERDUE and VOID are DISPLAY-DERIVED states — computed at runtime, NOT persisted.
    -- OVERDUE = UNPAID + due_date < today
    -- VOID    = workflow_status = ARCHIVED + payment_status = UNPAID
    payment_status              TEXT NOT NULL DEFAULT 'UNPAID'
                                    CHECK (payment_status IN (
                                        'UNPAID',
                                        'PAID',
                                        'PARTIAL',
                                        'DISPUTED',
                                        'CANCELLED'
                                    )),

    -- Timestamp of the last payment_status change (ISO datetime).
    payment_updated_at          TEXT,

    -- User email or system identifier who changed payment_status.
    payment_updated_by          TEXT,

    -- ── I. Retry mechanics (3 fields) ───────────────────────────────────────

    -- Total transmission retries attempted across all attempts.
    retry_count                 INTEGER NOT NULL DEFAULT 0,

    -- Timestamp of most recent retry attempt (ISO datetime).
    last_retry_at               TEXT,

    -- Scheduled timestamp for next retry (ISO datetime). NULL = no retry scheduled.
    next_retry_at               TEXT,

    -- ── J. FIRS audit artefacts (3 fields) ──────────────────────────────────
    -- Concrete FIRS API response artefacts.
    -- transmission_status is the abstracted platform state; these are the raw receipts.

    -- FIRS confirmation/acknowledgement number.
    firs_confirmation           TEXT,

    -- Full FIRS API response payload (JSON blob). For audit and re-submission.
    firs_response_data          TEXT,

    -- Complete FIRS submission record (JSON). Stores BOTH:
    -- • outbound_payload: what was sent to FIRS (the request body)
    -- • inbound_payload:  what FIRS returned (full response)
    -- Written at transmission time. Immutable after first write.
    firs_submitted_payload      TEXT,

    -- QR code data generated by HELIUM at signing. Contains verification fingerprint.
    -- Rendered in invoice PDF. NOT generated by FIRS.
    qr_code_data                TEXT,

    -- ── K. Company / seller party (14 fields) ───────────────────────────────
    -- The SELLER is the party issuing the invoice.
    --   • For OUTBOUND:                  seller = TENANT (the Helium platform company)
    --   • For INBOUND / SELF_BILLED_*:   seller = COUNTERPARTY (the supplier)
    --
    -- company_id always identifies the Helium tenant regardless of direction.
    -- seller_* fields are audit-stable snapshots at commit time.
    --
    -- FIRS MAPPING: seller_* → accounting_supplier_party.*
    -- seller_address = street_name, seller_city = city_name (separate FIRS mandatory fields).

    -- Helium tenant identifier. NOT NULL — every invoice belongs to a tenant.
    company_id                  TEXT NOT NULL,

    -- Seller party record ID.
    -- OUTBOUND: tenant's own record identifier.
    -- INBOUND:  counterparty's record from customers.db.
    seller_id                   TEXT,

    -- FIRS-registered Business ID for the seller. Immutable snapshot at commit time.
    -- Top-level field in FIRS payload: { "business_id": "..." }.
    -- Separate from TIN/Tax ID — this is the FIRS platform registration identifier.
    -- Stored per-invoice for audit: if business_id changes, old invoices retain the value
    -- that was active at the time of creation/submission.
    seller_business_id          TEXT,

    seller_name                 TEXT,

    -- Legacy TIN (########-####). One of three accepted FIRS tax identifiers.
    seller_tin                  TEXT,

    -- FIRS New 13-digit Tax ID. One of three accepted FIRS tax identifiers.
    seller_tax_id               TEXT,

    -- CAC RC Number (13 digits). One of three accepted FIRS tax identifiers.
    seller_rc_number            TEXT,

    seller_email                TEXT,

    -- Phone with country code (e.g. +2348012345678).
    seller_phone                TEXT,

    -- Street address (free-text). Maps to FIRS postal_address.street_name (max 200 chars).
    seller_address              TEXT,

    -- City or town name. Maps to FIRS postal_address.city_name (max 100 chars).
    -- Separate field because FIRS requires city_name as a mandatory standalone value.
    seller_city                 TEXT,

    seller_postal_code          TEXT,

    -- FIRS LGA code (1–774). Validated at application layer, not CHECK.
    seller_lga_code             TEXT,

    -- FIRS state code (1–37: 36 states + FCT).
    seller_state_code           TEXT,

    -- ISO 3166-1 alpha-2 country code. Default 'NG' for Nigeria.
    seller_country_code         TEXT DEFAULT 'NG',

    -- ── L. Buyer party (13 fields) ──────────────────────────────────────────
    -- The BUYER is the party receiving/paying for the invoice.
    --   • For OUTBOUND:                  buyer = COUNTERPARTY (the customer)
    --   • For INBOUND / SELF_BILLED_*:   buyer = TENANT (the Helium platform company)
    --
    -- buyer_* fields are audit-stable snapshots at commit time.
    -- Frontend always displays the counterparty side as "Customer" regardless
    -- of direction. For OUTBOUND → reads buyer_name. For INBOUND → reads seller_name.
    --
    -- FIRS MAPPING: buyer_* → accounting_customer_party.*
    --   (conditional mandatory for B2B: tin, email, postal_address required)
    -- buyer_address = street_name, buyer_city = city_name (separate FIRS mandatory fields).

    buyer_id                    TEXT,

    -- FIRS-registered Business ID for the buyer. Immutable snapshot at commit time.
    -- Top-level field in FIRS payload: { "business_id": "..." }.
    -- Separate from TIN/Tax ID — this is the FIRS platform registration identifier.
    -- Stored per-invoice for audit: if business_id changes, old invoices retain the value
    -- that was active at the time of creation/submission.
    buyer_business_id           TEXT,

    buyer_name                  TEXT,

    -- Legacy TIN (########-####).
    buyer_tin                   TEXT,

    -- FIRS New 13-digit Tax ID.
    buyer_tax_id                TEXT,

    -- CAC RC Number (13 digits).
    buyer_rc_number             TEXT,

    buyer_email                 TEXT,

    -- Phone with country code.
    buyer_phone                 TEXT,

    -- Street address (free-text). Maps to FIRS postal_address.street_name (max 200 chars).
    buyer_address               TEXT,

    -- City or town name. Maps to FIRS postal_address.city_name (max 100 chars).
    buyer_city                  TEXT,

    buyer_postal_code           TEXT,

    -- FIRS LGA code (1–774).
    buyer_lga_code              TEXT,

    -- FIRS state code (1–37).
    buyer_state_code            TEXT,

    -- ISO 3166-1 alpha-2 country code.
    buyer_country_code          TEXT DEFAULT 'NG',

    -- ── M. User (4 fields) ──────────────────────────────────────────────────

    -- HeartBeat-assigned user ID, immutable. From JWT sub claim.
    helium_user_id              TEXT,

    -- User email at time of submission (denormalized for audit trail stability).
    user_email                  TEXT,

    -- User display name at time of submission.
    user_name                   TEXT,

    -- Compat alias for helium_user_id, populated by API ingestion paths.
    created_by                  TEXT,

    -- ── N. Queue / batch / blob source references (5 fields) ────────────────

    -- Core queue entry identifier. Links to core_queue table.
    queue_id                    TEXT UNIQUE,

    -- Relay batch identifier. One batch → many invoices/files.
    batch_id                    TEXT,

    -- Individual source file identifier (Relay-assigned at ingestion).
    file_id                     TEXT,

    -- Object storage identifier (HeartBeat-assigned). Points to the raw source file.
    blob_uuid                   TEXT,

    -- Blob UUID for the Helium-stamped ("fixed") PDF generated post-finalize.
    -- NULL until PDF stamper runs. Points to HeartBeat blob store.
    fixed_invoice_blob_uuid     TEXT,

    -- Original filename of the source document.
    original_filename           TEXT,

    -- ── O. Source system context (2 fields) ──────────────────────────────────

    -- Channel or system that originated this invoice (e.g. 'bulk_upload', 'api', 'email').
    source                      TEXT,

    -- Record identifier in the originating external system.
    source_id                   TEXT,

    -- ── P. Display / SWDB fields (4 fields) ─────────────────────────────────
    -- These fields support the eInvoices tab spreadsheet display.

    -- For credit/debit notes: the original invoice number being referenced.
    -- Denormalized for fast display. Full reference chain in invoice_references table.
    reference                   TEXT,

    -- REMOVED in v2.1.3.0: category (invoice-level category scrapped — per-line-item only
    -- via product_category / service_category on invoice_line_items table)

    -- Payment terms description (e.g. "Net 30", "Immediate", "Net 60").
    terms                       TEXT,

    -- Count of attachments. Maintained by trigger on invoice_attachments.
    -- Used to render the attachment indicator in SWDB.
    attachment_count            INTEGER NOT NULL DEFAULT 0,

    -- ── Q. Notes (2 fields) ─────────────────────────────────────────────────

    -- Formal remarks submitted in the FIRS payload.
    -- Maps to FIRS `note` field (max 500 chars). FIRS encrypts this in storage.
    notes_to_firs               TEXT,

    -- Free text payment terms description.
    -- Maps to FIRS `payment_terms_note` field (max 500 chars).
    payment_terms_note          TEXT,

    -- ── Q2. ReviewPage fields (6 fields) ──────────────────────────────────
    -- Added v2.1.2.0 for ReviewPage rendering and SWDB display.

    -- Computed summary of line items for ReviewPage Product Description column.
    -- Format: "Item 1 (+N more)" for multi-line invoices, or just item name for single-line.
    product_summary             TEXT,

    -- Count of line items in this invoice. "1" for single-line, "3" for 3 items, etc.
    line_items_count            INTEGER DEFAULT 0,

    -- Count of free-of-charge (zero-price) line items. Used by FOC sheet.
    foc_line_count              INTEGER DEFAULT 0,

    -- Source file identification. For Excel: "workbook.xlsx / Sheet Name".
    -- For CSV/JSON/XML: just the filename.
    document_source             TEXT,

    -- Combined other taxes (WHT, levies, excise) excluding VAT.
    -- Separate from tax_amount which is VAT only.
    other_taxes                 REAL DEFAULT 0,

    -- Optional custom duties amount. NULL when not applicable.
    custom_duties               REAL,

    -- ── Q2. Commit-time customer snapshots (3 fields) ─────────────────────
    -- Frozen at COMMITTED transition. Audit self-containment: the invoice
    -- carries the customer's profile as it was at commit time, immune to
    -- later customer edits. Core's record_creator populates these.

    -- Total invoices for this customer at commit time. For "frequency" risk signals.
    customer_total_invoices_at_commit INTEGER,

    -- Cumulative revenue from this customer at commit time (in document currency).
    customer_lifetime_value_at_commit REAL,

    -- Compliance score (0–100) for this customer at commit time.
    customer_compliance_score_at_commit INTEGER,

    -- ── R. Inbound invoice fields (7 fields) ────────────────────────────────
    -- Required when direction = 'INBOUND'. NULL for OUTBOUND invoices.
    --
    -- UI NOTE: For inbound invoices, the SWDB "Status" column displays
    -- inbound_status (PENDING_REVIEW / ACCEPTED / REJECTED / EXPIRED)
    -- instead of workflow_status. The column renders as an authenticated
    -- dropdown that elevated users can interact with to accept/reject.
    -- Flow: Float App → SDK → Core → Edge → FIRS.
    -- The 72-hour action deadline is COMPUTED from inbound_received_at + 72h.
    -- Do NOT persist the computed deadline — calculate it at runtime.

    -- Timestamp when this invoice was received/ingested by Helium.
    inbound_received_at         TEXT,

    -- Current state of the inbound review process.
    -- Default: PENDING_REVIEW on arrival.
    -- Tenant (elevated user) must accept or reject within 72 hours.
    inbound_status              TEXT CHECK (inbound_status IN (
                                    'PENDING_REVIEW',
                                    'ACCEPTED',
                                    'REJECTED',
                                    'EXPIRED'
                                )),

    -- When the user took action (accepted/rejected).
    inbound_action_at           TEXT,

    -- Internal user ID who accepted/rejected.
    inbound_action_by_user_id   TEXT,

    -- User email at time of action (audit-stable).
    inbound_action_by_user_email TEXT,

    -- Required when inbound_status IN ('ACCEPTED', 'REJECTED').
    -- Must capture the business reason for the decision.
    inbound_action_reason       TEXT,

    -- Full source payload snapshot (JSON). Immutable after first write.
    -- Required for audit trail and potential re-processing.
    inbound_payload_json        TEXT,

    -- Number of reminders sent for this inbound invoice's 72-hour deadline.
    -- Incremented when the system sends expiry reminders to the tenant.
    -- Not applicable for OUTBOUND invoices (remains 0).
    reminder_count              INTEGER NOT NULL DEFAULT 0,

    -- ── S. Processing telemetry (4 fields) ──────────────────────────────────

    finalized_at                TEXT,
    processing_started_at       TEXT,
    processing_completed_at     TEXT,
    processing_duration_ms      INTEGER,

    -- ── T. Audit (4 fields) ─────────────────────────────────────────────────

    -- IMMUTABLE: set at first commit, never updated.
    -- All SLA windows, report chronology, and audit trails anchor to this.
    created_at                  TEXT NOT NULL DEFAULT (datetime('now')),

    -- Updated on every modification. Used for sync conflict resolution.
    updated_at                  TEXT NOT NULL DEFAULT (datetime('now')),

    -- Soft delete timestamp. 24-hour recovery window before HeartBeat hard-deletes.
    deleted_at                  TEXT,
    deleted_by                  TEXT,

    -- ── U. Machine & Session Context (5 fields) ──────────────────────────
    -- Per HELIUM_SECURITY_SPEC: composite machine fingerprint + session context.
    -- Propagated from the original upload through blob → invoice pipeline.

    -- Windows MachineGuid / Linux machine-id. Primary machine identity anchor.
    machine_guid                TEXT,

    -- Primary NIC MAC address. Corroborating identity signal. Format: XX:XX:XX:XX:XX:XX.
    mac_address                 TEXT,

    -- OS hostname. Human-readable label only, NOT used for identity matching.
    computer_name               TEXT,

    -- HeartBeat-assigned Float instance ID. From JWT, tied to machine at registration.
    float_id                    TEXT,

    -- Session UUID active at invoice creation/submission. Resets at hard re-auth (8 hours).
    session_id                  TEXT
);

-- ── Indexes for invoices ────────────────────────────────────────────────────

-- Primary lookups
CREATE INDEX idx_inv_invoice_id         ON invoices(invoice_id);
CREATE INDEX idx_inv_helium_no          ON invoices(helium_invoice_no);
CREATE INDEX idx_inv_invoice_number     ON invoices(invoice_number);
CREATE INDEX idx_inv_irn                ON invoices(irn) WHERE irn IS NOT NULL;
CREATE INDEX idx_inv_queue_id           ON invoices(queue_id) WHERE queue_id IS NOT NULL;
CREATE INDEX idx_inv_batch_id           ON invoices(batch_id) WHERE batch_id IS NOT NULL;
CREATE INDEX idx_inv_blob_uuid          ON invoices(blob_uuid) WHERE blob_uuid IS NOT NULL;

-- Party lookups
CREATE INDEX idx_inv_company_id         ON invoices(company_id);
CREATE INDEX idx_inv_seller_id          ON invoices(seller_id) WHERE seller_id IS NOT NULL;
CREATE INDEX idx_inv_buyer_id           ON invoices(buyer_id) WHERE buyer_id IS NOT NULL;

-- Status lookups
CREATE INDEX idx_inv_workflow_status    ON invoices(workflow_status);
CREATE INDEX idx_inv_transmission_status ON invoices(transmission_status);
CREATE INDEX idx_inv_payment_status     ON invoices(payment_status);

-- Classifier lookups
CREATE INDEX idx_inv_direction          ON invoices(direction);
CREATE INDEX idx_inv_document_type      ON invoices(document_type);
CREATE INDEX idx_inv_transaction_type   ON invoices(transaction_type);

-- Date lookups
CREATE INDEX idx_inv_issue_date         ON invoices(issue_date);
CREATE INDEX idx_inv_due_date           ON invoices(due_date) WHERE due_date IS NOT NULL;
CREATE INDEX idx_inv_payment_due_date   ON invoices(payment_due_date) WHERE payment_due_date IS NOT NULL;
CREATE INDEX idx_inv_sign_date          ON invoices(sign_date) WHERE sign_date IS NOT NULL;
CREATE INDEX idx_inv_transmission_date  ON invoices(transmission_date) WHERE transmission_date IS NOT NULL;

-- Audit / chronology
CREATE INDEX idx_inv_created_at         ON invoices(created_at DESC);
CREATE INDEX idx_inv_updated_at         ON invoices(updated_at DESC);
CREATE INDEX idx_inv_deleted_at         ON invoices(deleted_at) WHERE deleted_at IS NOT NULL;

-- Composite indexes for common query patterns
CREATE INDEX idx_inv_company_status     ON invoices(company_id, workflow_status);
CREATE INDEX idx_inv_company_direction  ON invoices(company_id, direction);
CREATE INDEX idx_inv_status_date        ON invoices(workflow_status, created_at DESC);
CREATE INDEX idx_inv_payment_due        ON invoices(payment_status, payment_due_date) WHERE payment_due_date IS NOT NULL;
CREATE INDEX idx_inv_inbound_review     ON invoices(direction, inbound_status) WHERE direction = 'INBOUND';

-- v2.2 party / IBN indexes
CREATE INDEX idx_inv_seller_state       ON invoices(seller_state_code) WHERE seller_state_code IS NOT NULL;
CREATE INDEX idx_inv_seller_lga         ON invoices(seller_lga_code) WHERE seller_lga_code IS NOT NULL;
CREATE INDEX idx_inv_buyer_state        ON invoices(buyer_state_code) WHERE buyer_state_code IS NOT NULL;
CREATE INDEX idx_inv_buyer_lga          ON invoices(buyer_lga_code) WHERE buyer_lga_code IS NOT NULL;
CREATE INDEX idx_inv_has_discount       ON invoices(has_discount) WHERE has_discount = 1;
CREATE INDEX idx_inv_wht_amount         ON invoices(wht_amount) WHERE wht_amount IS NOT NULL;
CREATE INDEX idx_inv_payment_means      ON invoices(payment_means) WHERE payment_means IS NOT NULL;
CREATE INDEX idx_inv_po_number          ON invoices(purchase_order_number) WHERE purchase_order_number IS NOT NULL;

-- v2.1.1.0 Security spec: trace chain, identity, session indexes
CREATE INDEX IF NOT EXISTS idx_invoices_invoice_trace ON invoices (invoice_trace_id);
CREATE INDEX IF NOT EXISTS idx_invoices_x_trace ON invoices (x_trace_id);
CREATE INDEX IF NOT EXISTS idx_invoices_helium_user ON invoices (helium_user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_machine ON invoices (machine_guid);
CREATE INDEX IF NOT EXISTS idx_invoices_float ON invoices (float_id);


-- Trigger: auto-update updated_at on modification
CREATE TRIGGER trg_invoices_updated_at
AFTER UPDATE ON invoices
BEGIN
    UPDATE invoices SET updated_at = datetime('now') WHERE id = NEW.id;
END;


-- ============================================================================
-- TABLE 2: invoice_line_items (21 fields)
-- ============================================================================

CREATE TABLE invoice_line_items (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    -- UUID-style line ID for SDK compat (allows addressing lines without integer PK).
    line_id                     TEXT UNIQUE,

    -- Parent invoice (integer FK for performance).
    invoice_id                  INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,

    -- Display order within the invoice.
    line_number                 INTEGER NOT NULL,

    -- GOODS: physical product with HSN code.
    -- SERVICE: service with service code.
    -- Determines which classification fields are required below.
    line_item_type              TEXT NOT NULL DEFAULT 'GOODS'
                                    CHECK (line_item_type IN ('GOODS', 'SERVICE')),

    -- ── Common fields ──────────────────────────────────────────────────────
    -- description maps to FIRS invoice_line[].item.name (max 500 chars).
    description                 TEXT NOT NULL,
    quantity                    REAL NOT NULL CHECK (quantity > 0),
    unit_price                  REAL NOT NULL CHECK (unit_price >= 0),
    line_total                  REAL NOT NULL,        -- quantity × unit_price (pre-tax)
    tax_rate                    REAL DEFAULT 0.0,     -- e.g. 0.075 for 7.5% VAT
    tax_amount                  REAL DEFAULT 0.0,

    -- ── Goods classification (required when line_item_type = 'GOODS') ──────
    -- HS/HSN code in XXXX.XX format (6-digit with period, per FIRS standard).
    -- Maps to FIRS invoice_line[].hsn_code.
    hsn_code                    TEXT,

    -- Human-readable product category (from PDP classification).
    product_category            TEXT,

    -- ── Service classification (required when line_item_type = 'SERVICE') ──
    -- ISIC or FIRS service code.
    service_code                TEXT,

    -- Human-readable service category.
    service_category            TEXT,

    -- ── Product reference (application-level FK to inventory.db) ──────────
    product_id                  TEXT,
    -- Seller's internal SKU. Maps to FIRS sellers_item_identification.
    product_code                TEXT,
    product_name                TEXT,

    -- ── Audit self-containment (5 fields, v2.1.3.0) ──────────────────────
    -- Snapshot fields frozen at commit time. The line item carries enough
    -- context to be auditable without JOINing inventory/customer tables.

    -- Customer's own SKU for this product (from inventory.customer_sku).
    customer_sku                TEXT,

    -- OEM/manufacturer SKU (from inventory.oem_sku).
    oem_sku                     TEXT,

    -- Helium-assigned SKU (from inventory.helium_sku).
    helium_sku                  TEXT,

    -- Extended product/service description (from inventory.full_description).
    -- Longer than description; used in detailed audit views.
    full_description            TEXT,

    -- VAT rate as a percentage (e.g. 7.5 for 7.5%). Snapshot from inventory/tax config.
    -- Distinct from tax_rate which is the decimal form (0.075).
    vat_rate                    REAL,

    -- ── PDP classification intelligence ───────────────────────────────────
    -- Confidence score from PDP/LLM classification (0.0 – 1.0).
    classification_confidence   REAL,

    -- Source of the classification ('pdp', 'manual', 'llm', 'user_override').
    classification_source       TEXT,

    created_at                  TEXT NOT NULL DEFAULT (datetime('now')),

    UNIQUE (invoice_id, line_number)
);

CREATE INDEX idx_lines_invoice_id   ON invoice_line_items(invoice_id);
CREATE INDEX idx_lines_product_id   ON invoice_line_items(product_id) WHERE product_id IS NOT NULL;
CREATE INDEX idx_lines_hsn_code     ON invoice_line_items(hsn_code) WHERE hsn_code IS NOT NULL;
CREATE INDEX idx_lines_type         ON invoice_line_items(line_item_type);


-- ============================================================================
-- TABLE 3: invoice_references (7 fields)
-- Purpose: Links invoice to prior invoices (credit/debit note chains, origin refs).
-- ============================================================================

CREATE TABLE invoice_references (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Parent invoice that is MAKING the reference.
    invoice_id                  INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,

    -- CREDIT_NOTE  = this invoice corrects/cancels a prior invoice
    -- DEBIT_NOTE   = this invoice increases a prior invoice amount
    -- ORIGIN       = general "relates to" reference
    -- ORDER        = links to a purchase order
    reference_type              TEXT NOT NULL
                                    CHECK (reference_type IN (
                                        'CREDIT_NOTE', 'DEBIT_NOTE', 'ORIGIN', 'ORDER'
                                    )),

    -- Internal Helium invoice_id of the referenced invoice (if known in system).
    reference_invoice_id        TEXT,

    -- IRN of the referenced invoice (for compliance payload).
    reference_irn               TEXT,

    -- Issue date of the referenced invoice (for compliance payload).
    reference_issue_date        TEXT,

    created_at                  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_refs_invoice_id        ON invoice_references(invoice_id);
CREATE INDEX idx_refs_ref_invoice_id    ON invoice_references(reference_invoice_id) WHERE reference_invoice_id IS NOT NULL;
CREATE INDEX idx_refs_ref_irn           ON invoice_references(reference_irn) WHERE reference_irn IS NOT NULL;


-- ============================================================================
-- TABLE 4: invoice_tax_categories (7 fields)
-- Purpose: One invoice can have MULTIPLE tax categories applied across its
--          line items. This table stores the per-category tax breakdown.
--          Tax category codes match the FIRS/NRS API enum (24 values + NEPZA + WITHHOLDING_TAX).
--          Maps to: tax_total[].tax_subtotal[].tax_category in FIRS payload.
-- ============================================================================

CREATE TABLE invoice_tax_categories (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    invoice_id                  INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,

    -- FIRS/NRS tax category code (26 values: 24 FIRS API + NEPZA + WITHHOLDING_TAX).
    tax_category                TEXT NOT NULL
                                    CHECK (tax_category IN (
                                        'STANDARD_GST',
                                        'REDUCED_GST',
                                        'ZERO_GST',
                                        'STANDARD_VAT',
                                        'REDUCED_VAT',
                                        'ZERO_VAT',
                                        'STATE_SALES_TAX',
                                        'LOCAL_SALES_TAX',
                                        'ALCOHOL_EXCISE_TAX',
                                        'TOBACCO_EXCISE_TAX',
                                        'FUEL_EXCISE_TAX',
                                        'CORPORATE_INCOME_TAX',
                                        'PERSONAL_INCOME_TAX',
                                        'SOCIAL_SECURITY_TAX',
                                        'MEDICARE_TAX',
                                        'REAL_ESTATE_TAX',
                                        'PERSONAL_PROPERTY_TAX',
                                        'CARBON_TAX',
                                        'PLASTIC_TAX',
                                        'IMPORT_DUTY',
                                        'EXPORT_DUTY',
                                        'LUXURY_TAX',
                                        'SERVICE_TAX',
                                        'TOURISM_TAX',
                                        'NEPZA',
                                        'WITHHOLDING_TAX'
                                    )),

    -- Applicable tax rate for this category as decimal (e.g. 0.075 for 7.5%).
    -- Edge multiplies by 100 to send percent to FIRS (e.g. 7.5).
    tax_rate                    REAL NOT NULL DEFAULT 0.075,

    -- Sum of taxable line item amounts under this category.
    taxable_amount              REAL NOT NULL DEFAULT 0.0,

    -- Total tax computed for this category (taxable_amount × tax_rate).
    tax_amount                  REAL NOT NULL DEFAULT 0.0,

    created_at                  TEXT NOT NULL DEFAULT (datetime('now')),

    UNIQUE (invoice_id, tax_category)
);

CREATE INDEX idx_tax_cat_invoice_id     ON invoice_tax_categories(invoice_id);
CREATE INDEX idx_tax_cat_category       ON invoice_tax_categories(tax_category);


-- ============================================================================
-- TABLE 5: invoice_attachments (9 fields)
-- Purpose: Pointers to supplementary files. Actual bytes live in object storage.
-- ============================================================================

CREATE TABLE invoice_attachments (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    invoice_id                  INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,

    attachment_type             TEXT,           -- e.g. 'SUPPORTING_DOC', 'DELIVERY_NOTE'
    filename                    TEXT NOT NULL,
    blob_uuid                   TEXT NOT NULL,  -- Object storage (HeartBeat) reference
    file_size_bytes             INTEGER,
    mime_type                   TEXT,

    uploaded_by                 TEXT,
    uploaded_at                 TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_attach_invoice_id  ON invoice_attachments(invoice_id);
CREATE INDEX idx_attach_blob_uuid   ON invoice_attachments(blob_uuid);

-- Trigger: maintain attachment_count on invoices
CREATE TRIGGER trg_attach_count_insert
AFTER INSERT ON invoice_attachments
BEGIN
    UPDATE invoices SET attachment_count = attachment_count + 1 WHERE id = NEW.invoice_id;
END;

CREATE TRIGGER trg_attach_count_delete
AFTER DELETE ON invoice_attachments
BEGIN
    UPDATE invoices SET attachment_count = MAX(0, attachment_count - 1) WHERE id = OLD.invoice_id;
END;


-- ============================================================================
-- TABLE 6: invoice_transmission_attempts (10 fields)
-- Purpose: Structured per-attempt telemetry for retry analytics and SLA tracking.
--          Edge writes through controlled contract; Core reads for observability.
-- ============================================================================

CREATE TABLE invoice_transmission_attempts (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    invoice_id                  INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,

    -- Monotonically increasing attempt counter per invoice.
    attempt_no                  INTEGER NOT NULL,

    -- When the attempt was initiated.
    attempted_at                TEXT NOT NULL DEFAULT (datetime('now')),

    -- Outcome of this specific attempt.
    result_status               TEXT NOT NULL
                                    CHECK (result_status IN (
                                        'SUCCESS',
                                        'RETRYABLE_FAILURE',
                                        'TERMINAL_FAILURE'
                                    )),

    -- Error classification for analytics and alerting.
    error_category              TEXT CHECK (error_category IN (
                                    'NETWORK', 'AUTH', 'VALIDATION',
                                    'PROVIDER', 'TIMEOUT', 'UNKNOWN'
                                )),

    -- Raw response code from FIRS/NRS/counterparty.
    response_code               TEXT,

    -- Human-readable response message.
    response_message            TEXT,

    -- Trace ID for this specific attempt (may differ from parent invoice invoice_trace_id).
    trace_id                    TEXT,

    -- Optional: request/response payload snapshot for debugging.
    payload_json                TEXT,

    UNIQUE (invoice_id, attempt_no)
);

CREATE INDEX idx_attempts_invoice_id    ON invoice_transmission_attempts(invoice_id);
CREATE INDEX idx_attempts_result        ON invoice_transmission_attempts(result_status);
CREATE INDEX idx_attempts_attempted_at  ON invoice_transmission_attempts(attempted_at DESC);
-- actor_service removed (v2.1.0.1 cleanup). Retry initiation tracking TBD.


-- ============================================================================
-- TABLE 7: invoice_allowance_charges (10 fields)
-- Purpose: Stores FIRS allowance_charge[] entries for audit round-tripping.
--          Allowances (discounts) and charges (surcharges) at invoice or line level.
--          Maps to: allowance_charge[] in FIRS payload.
--          Added in v2.1.0.2 — gap closure from Transforma payload audit.
-- ============================================================================

CREATE TABLE invoice_allowance_charges (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    invoice_id                  INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,

    -- NULL = invoice-level allowance/charge.
    -- Non-NULL = line-level, FK to invoice_line_items.id.
    line_item_id                INTEGER REFERENCES invoice_line_items(id) ON DELETE CASCADE,

    -- true (1) = charge/surcharge, false (0) = allowance/discount.
    -- Maps to FIRS allowance_charge[].charge_indicator.
    charge_indicator            INTEGER NOT NULL DEFAULT 0,

    -- Human-readable reason. Maps to FIRS allowance_charge[].allowance_charge_reason.
    reason                      TEXT,

    -- Allowance/charge monetary amount.
    amount                      REAL NOT NULL DEFAULT 0.0,

    -- Base amount the allowance/charge was calculated against (nullable).
    -- Maps to FIRS allowance_charge[].base_amount.
    base_amount                 REAL,

    -- Tax category applicable to this allowance/charge (nullable).
    -- Uses same enum as invoice_tax_categories.
    tax_category                TEXT,

    -- Tax rate as decimal (e.g. 0.075).
    tax_rate                    REAL,

    created_at                  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_ac_invoice_id          ON invoice_allowance_charges(invoice_id);
CREATE INDEX idx_ac_line_item           ON invoice_allowance_charges(line_item_id) WHERE line_item_id IS NOT NULL;


-- ============================================================================
-- TABLE 8: invoice_history (9 fields)
-- Purpose: Field-level audit trail. One row per changed field per change event.
-- ============================================================================

CREATE TABLE invoice_history (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    invoice_id                  INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,

    -- 'CREATED' | 'UPDATED' | 'STATUS_CHANGE' | 'SOFT_DELETED' | 'RESTORED'
    change_type                 TEXT NOT NULL,

    -- Name of the field that changed (NULL for CREATED events).
    changed_field               TEXT,

    -- Previous value (serialized as TEXT).
    old_value                   TEXT,

    -- New value (serialized as TEXT).
    new_value                   TEXT,

    changed_by                  TEXT,
    changed_at                  TEXT NOT NULL DEFAULT (datetime('now')),
    change_reason               TEXT
);

CREATE INDEX idx_hist_invoice_id    ON invoice_history(invoice_id);
CREATE INDEX idx_hist_changed_at    ON invoice_history(changed_at DESC);
CREATE INDEX idx_hist_field         ON invoice_history(changed_field) WHERE changed_field IS NOT NULL;


-- ── TABLE 9: tenant_invoice_metrics (v2.1.3.0) ─────────────────────────────
-- Materialized aggregate counters per tenant. Populated by Core's aggregate
-- worker (Session 2B). Read by SDK for dashboard statistics.
-- NOT a view — precomputed for performance. Refreshed on invoice status changes.

CREATE TABLE tenant_invoice_metrics (
    id                          INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Tenant anchor. One row per company.
    company_id                  TEXT NOT NULL UNIQUE,

    -- Total invoice counts by direction
    total_outbound              INTEGER NOT NULL DEFAULT 0,
    total_inbound               INTEGER NOT NULL DEFAULT 0,

    -- Financial aggregates (in document currency, typically NGN)
    total_revenue               REAL NOT NULL DEFAULT 0,
    total_tax_collected         REAL NOT NULL DEFAULT 0,

    -- Payment health
    unpaid_count                INTEGER NOT NULL DEFAULT 0,
    paid_count                  INTEGER NOT NULL DEFAULT 0,
    overdue_count               INTEGER NOT NULL DEFAULT 0,

    -- Transmission health
    transmitted_count           INTEGER NOT NULL DEFAULT 0,
    rejected_count              INTEGER NOT NULL DEFAULT 0,
    failed_count                INTEGER NOT NULL DEFAULT 0,

    -- Period counters (current calendar month)
    invoices_this_month         INTEGER NOT NULL DEFAULT 0,
    revenue_this_month          REAL NOT NULL DEFAULT 0,

    -- Refresh tracking
    last_refreshed_at           TEXT NOT NULL DEFAULT (datetime('now')),
    refresh_count               INTEGER NOT NULL DEFAULT 0,

    created_at                  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at                  TEXT NOT NULL DEFAULT (datetime('now'))
);


-- ============================================================================
-- TRIGGERS: audit log on invoices
-- ============================================================================

-- Trigger: auto-create audit log on INSERT
CREATE TRIGGER trg_audit_invoice_insert
AFTER INSERT ON invoices
BEGIN
    INSERT INTO invoice_history (
        invoice_id, change_type, changed_by, change_reason, new_value
    ) VALUES (
        NEW.id,
        'CREATED',
        COALESCE(NEW.helium_user_id, NEW.created_by),
        'Invoice committed',
        json_object(
            'invoice_id',       NEW.invoice_id,
            'helium_invoice_no',NEW.helium_invoice_no,
            'invoice_number',   NEW.invoice_number,
            'direction',        NEW.direction,
            'document_type',    NEW.document_type,
            'transaction_type', NEW.transaction_type,
            'total_amount',     NEW.total_amount,
            'workflow_status',  NEW.workflow_status,
            'seller_name',      NEW.seller_name,
            'buyer_name',       NEW.buyer_name
        )
    );
END;

-- Trigger: workflow_status change tracking
CREATE TRIGGER trg_audit_workflow_status
AFTER UPDATE OF workflow_status ON invoices
WHEN OLD.workflow_status != NEW.workflow_status
BEGIN
    INSERT INTO invoice_history (
        invoice_id, change_type, changed_field, old_value, new_value,
        changed_by, change_reason
    ) VALUES (
        NEW.id,
        'STATUS_CHANGE',
        'workflow_status',
        OLD.workflow_status,
        NEW.workflow_status,
        COALESCE(NEW.helium_user_id, NEW.created_by),
        NULL
    );
END;

-- Trigger: payment_status change tracking
CREATE TRIGGER trg_audit_payment_status
AFTER UPDATE OF payment_status ON invoices
WHEN OLD.payment_status != NEW.payment_status
BEGIN
    INSERT INTO invoice_history (
        invoice_id, change_type, changed_field, old_value, new_value,
        changed_by, change_reason
    ) VALUES (
        NEW.id,
        'STATUS_CHANGE',
        'payment_status',
        OLD.payment_status,
        NEW.payment_status,
        COALESCE(NEW.helium_user_id, NEW.created_by),
        NULL
    );
END;

-- Trigger: inbound_status change tracking
CREATE TRIGGER trg_audit_inbound_status
AFTER UPDATE OF inbound_status ON invoices
WHEN OLD.inbound_status IS NOT NEW.inbound_status
     OR (OLD.inbound_status IS NULL AND NEW.inbound_status IS NOT NULL)
BEGIN
    INSERT INTO invoice_history (
        invoice_id, change_type, changed_field, old_value, new_value,
        changed_by, change_reason
    ) VALUES (
        NEW.id,
        'STATUS_CHANGE',
        'inbound_status',
        OLD.inbound_status,
        NEW.inbound_status,
        NEW.inbound_action_by_user_id,
        NEW.inbound_action_reason
    );
END;

-- Trigger: soft-delete tracking
CREATE TRIGGER trg_audit_soft_delete
AFTER UPDATE OF deleted_at ON invoices
WHEN NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL
BEGIN
    INSERT INTO invoice_history (
        invoice_id, change_type, changed_by, old_value
    ) VALUES (
        NEW.id,
        'SOFT_DELETED',
        NEW.deleted_by,
        json_object('workflow_status', OLD.workflow_status, 'total_amount', OLD.total_amount)
    );
END;


-- ============================================================================
-- VIEW: vw_invoices_summary
-- Purpose: Basic statistics for SWDB stats bar.
-- ============================================================================

CREATE VIEW IF NOT EXISTS vw_invoices_summary AS
SELECT
    COUNT(*)                                                        AS total_count,
    SUM(CASE WHEN workflow_status = 'COMMITTED'    THEN 1 ELSE 0 END) AS committed_count,
    SUM(CASE WHEN workflow_status = 'QUEUED'       THEN 1 ELSE 0 END) AS queued_count,
    SUM(CASE WHEN workflow_status = 'TRANSMITTING' THEN 1 ELSE 0 END) AS transmitting_count,
    SUM(CASE WHEN workflow_status = 'TRANSMITTED'  THEN 1 ELSE 0 END) AS transmitted_count,
    SUM(CASE WHEN workflow_status = 'VALIDATED'    THEN 1 ELSE 0 END) AS validated_count,
    SUM(CASE WHEN workflow_status = 'ERROR'        THEN 1 ELSE 0 END) AS error_count,
    SUM(CASE WHEN workflow_status = 'ARCHIVED'     THEN 1 ELSE 0 END) AS archived_count,
    SUM(total_amount)                                               AS total_amount,
    AVG(total_amount)                                               AS average_amount,
    MIN(created_at)                                                 AS oldest_invoice_date,
    MAX(created_at)                                                 AS latest_invoice_date,
    COUNT(DISTINCT buyer_id)                                        AS unique_buyers,
    COUNT(DISTINCT seller_id)                                       AS unique_sellers
FROM invoices
WHERE deleted_at IS NULL;


-- ============================================================================
-- VIEW: vw_invoice_metrics
-- Purpose: Time-windowed analytics for SWDB stats bar and report engine.
-- ============================================================================

CREATE VIEW IF NOT EXISTS vw_invoice_metrics AS
SELECT
    -- ── Totals by direction ──────────────────────────────────────────────────
    COUNT(*)                                                            AS total_invoices,
    SUM(CASE WHEN direction = 'OUTBOUND' THEN 1 ELSE 0 END)            AS outbound_count,
    SUM(CASE WHEN direction = 'INBOUND'  THEN 1 ELSE 0 END)            AS inbound_count,

    -- ── Time windows ─────────────────────────────────────────────────────────
    SUM(CASE WHEN date(created_at) >= date('now', 'weekday 0', '-7 days')
             THEN 1 ELSE 0 END)                                        AS created_this_week,

    SUM(CASE WHEN strftime('%Y-%m', created_at) = strftime('%Y-%m', 'now')
             THEN 1 ELSE 0 END)                                        AS created_this_month,

    SUM(CASE WHEN strftime('%Y', created_at) = strftime('%Y', 'now')
              AND ((CAST(strftime('%m', created_at) AS INTEGER) - 1) / 3)
                = ((CAST(strftime('%m', 'now') AS INTEGER) - 1) / 3)
             THEN 1 ELSE 0 END)                                        AS created_this_quarter,

    -- ── Financial aggregates ─────────────────────────────────────────────────
    COALESCE(SUM(total_amount), 0.0)                                   AS total_gross_amount,
    COALESCE(SUM(tax_amount),   0.0)                                   AS total_tax_amount,

    COALESCE(SUM(CASE WHEN transmission_status IN ('TRANSMITTED', 'ACCEPTED')
                      THEN total_amount ELSE 0.0 END), 0.0)            AS total_transmitted_amount,

    COALESCE(SUM(CASE WHEN workflow_status = 'VALIDATED'
                      THEN total_amount ELSE 0.0 END), 0.0)            AS total_validated_amount,

    -- ── WHT & discount aggregates (v2.1.0.2) ─────────────────────────────────
    COALESCE(SUM(wht_amount), 0.0)                                     AS total_wht_amount,
    SUM(CASE WHEN wht_amount IS NOT NULL AND wht_amount > 0
             THEN 1 ELSE 0 END)                                        AS wht_invoice_count,
    COALESCE(SUM(discount_amount), 0.0)                                AS total_discount_amount,

    -- ── Payment health ───────────────────────────────────────────────────────
    SUM(CASE WHEN payment_status = 'UNPAID' THEN 1 ELSE 0 END)         AS unpaid_count,
    SUM(CASE WHEN payment_status = 'PAID'   THEN 1 ELSE 0 END)         AS paid_count,
    SUM(CASE WHEN payment_status = 'PARTIAL' THEN 1 ELSE 0 END)        AS partial_count,
    SUM(CASE WHEN payment_status = 'DISPUTED' THEN 1 ELSE 0 END)       AS disputed_count,

    -- Display-derived OVERDUE count (not persisted, computed here)
    SUM(CASE WHEN payment_status = 'UNPAID'
              AND due_date IS NOT NULL
              AND date(due_date) < date('now')
             THEN 1 ELSE 0 END)                                        AS overdue_count,

    -- ── Transmission health ──────────────────────────────────────────────────
    SUM(CASE WHEN transmission_status IN ('FAILED_RETRYABLE', 'FAILED_TERMINAL')
             THEN 1 ELSE 0 END)                                        AS failed_transmission_count,

    CASE WHEN COUNT(*) > 0
         THEN ROUND(100.0 * SUM(CASE WHEN transmission_status IN ('FAILED_RETRYABLE', 'FAILED_TERMINAL')
                                     THEN 1 ELSE 0 END) / COUNT(*), 1)
         ELSE 0.0 END                                                  AS failure_rate_pct,

    -- ── Inbound pending review ───────────────────────────────────────────────
    SUM(CASE WHEN direction = 'INBOUND' AND inbound_status = 'PENDING_REVIEW'
             THEN 1 ELSE 0 END)                                        AS inbound_pending_count,

    -- Inbound approaching 72h deadline (received > 48h ago, still pending)
    SUM(CASE WHEN direction = 'INBOUND'
              AND inbound_status = 'PENDING_REVIEW'
              AND inbound_received_at IS NOT NULL
              AND datetime(inbound_received_at, '+48 hours') < datetime('now')
             THEN 1 ELSE 0 END)                                        AS inbound_urgent_count

FROM invoices
WHERE deleted_at IS NULL;


-- ============================================================================
-- VIEW: vw_payment_variances
-- Purpose: Track discrepancies between document due_date and calculated payment_due_date.
-- ============================================================================

CREATE VIEW IF NOT EXISTS vw_payment_variances AS
SELECT
    id,
    invoice_id,
    helium_invoice_no,
    invoice_number,
    buyer_name,
    total_amount,
    due_date,
    payment_due_date,
    JULIANDAY(due_date) - JULIANDAY(payment_due_date) AS variance_days,
    CASE
        WHEN due_date IS NULL OR payment_due_date IS NULL THEN 'MISSING_DATE'
        WHEN due_date = payment_due_date THEN 'ALIGNED'
        WHEN JULIANDAY(due_date) > JULIANDAY(payment_due_date) THEN 'DOCUMENT_LATER'
        ELSE 'DOCUMENT_EARLIER'
    END AS variance_type
FROM invoices
WHERE deleted_at IS NULL
  AND (due_date IS NOT NULL OR payment_due_date IS NOT NULL);


-- ============================================================================
-- SCOPED ACCESS VIEWS (v2.1.2.0 — permission-ready field grouping)
-- These views organize the 115-field invoices table by access scope.
-- Permissions (GRANT/RLS) are layered on top per deployment — see
-- PostgreSQL ACL block below. SQLite enforcement is in SDK code.
-- ============================================================================


-- ============================================================================
-- VIEW: vw_invoice_firs
-- Purpose: 32 FIRS-mandatory fields for payload construction and audit.
-- Access:  Core (rw), Edge (r), SDK (r — SELECT only, no UPDATE path)
-- Fields:  26 FIRS signing + 5 B2B conditional + company_id tenant anchor
-- ============================================================================

CREATE VIEW IF NOT EXISTS vw_invoice_firs AS
SELECT
    -- Identity anchor
    id,
    invoice_id,
    company_id,

    -- FIRS Reference
    irn,

    -- Document classification (Section B)
    direction,
    document_type,
    firs_invoice_type_code,
    transaction_type,

    -- Dates (Section C)
    issue_date,
    issue_time,

    -- Currency (Section D)
    document_currency_code,
    tax_currency_code,

    -- Financial totals (Section D)
    subtotal,
    tax_amount,
    total_amount,

    -- Payment (Section E)
    payment_means,
    firs_payment_means_code,

    -- Seller party — 26 signing fields (Section K)
    seller_name,
    seller_tin,
    seller_address,
    seller_city,
    seller_state_code,
    seller_lga_code,
    seller_country_code,

    -- Buyer party — 26 signing + B2B conditional (Sections K/L)
    buyer_name,
    buyer_tin,
    buyer_address,
    buyer_city,

    -- B2B conditional fields (5)
    buyer_state_code,
    buyer_lga_code,
    buyer_country_code,
    purchase_order_number,
    contract_number

FROM invoices
WHERE deleted_at IS NULL;


-- ============================================================================
-- VIEW: vw_invoice_user_editable
-- Purpose: Permission-gated user-editable status fields.
-- Access:  SDK (SELECT + UPDATE payment_status, inbound_status only)
-- Note:    Inbound action fields travel with inbound_status as an atomic unit.
--          UPDATE via this view requires INSTEAD OF trigger on PostgreSQL
--          or underlying table grant. SQLite enforcement is code-level.
-- ============================================================================

CREATE VIEW IF NOT EXISTS vw_invoice_user_editable AS
SELECT
    id,
    invoice_id,
    helium_invoice_no,

    -- User-editable statuses (Section H / R)
    payment_status,
    inbound_status,

    -- Inbound action capture (set atomically with inbound_status)
    inbound_action_at,
    inbound_action_by_user_id,
    inbound_action_by_user_email,
    inbound_action_reason

FROM invoices
WHERE deleted_at IS NULL;


-- ============================================================================
-- VIEW: vw_invoice_system
-- Purpose: System-controlled lifecycle, retry mechanics, trace chain, telemetry.
-- Access:  Core (rw), Edge (rw: transmission fields only), SDK (r — read only)
-- ============================================================================

CREATE VIEW IF NOT EXISTS vw_invoice_system AS
SELECT
    id,
    invoice_id,
    helium_invoice_no,

    -- Trace chain — 3-level (Section A / U)
    invoice_trace_id,
    user_trace_id,
    x_trace_id,

    -- Workflow lifecycle (Section H)
    workflow_status,

    -- Processing telemetry (Section S)
    finalized_at,
    processing_started_at,
    processing_completed_at,
    processing_duration_ms,

    -- FIRS transmission — Edge controlled contract (Section H)
    transmission_status,
    transmission_status_error,
    transmission_date,
    acknowledgement_date,

    -- Retry mechanics (Section I)
    retry_count,
    last_retry_at,
    next_retry_at,

    -- FIRS artefacts (Section J)
    sign_date,
    csid,
    csid_status,
    firs_confirmation,
    firs_response_data,
    qr_code_data,

    -- Machine + session identity (Section U)
    machine_guid,
    mac_address,
    computer_name,
    float_id,
    session_id,

    -- Audit timestamps (Section T)
    created_at,
    updated_at

FROM invoices
WHERE deleted_at IS NULL;


-- ============================================================================
-- VIEW: vw_invoice_display
-- Purpose: UI-priority columns for SWDB eInvoices grid (fast grid render).
-- Access:  SDK (r — SELECT only)
-- Note:    counterparty_name is direction-aware:
--            OUTBOUND → buyer_name (we are seller, they are buyer)
--            INBOUND  → seller_name (they are seller, we are buyer)
-- ============================================================================

CREATE VIEW IF NOT EXISTS vw_invoice_display AS
SELECT
    id,
    invoice_id,
    helium_invoice_no,
    invoice_number,
    issue_date,
    direction,
    document_type,
    transaction_type,

    -- Direction-aware counterparty
    CASE WHEN direction = 'OUTBOUND'
         THEN buyer_name
         ELSE seller_name
    END AS counterparty_name,

    -- Status trio
    workflow_status,
    transmission_status,
    payment_status,

    -- Financial
    total_amount,
    document_currency_code,

    -- Due date
    payment_due_date,

    -- Inbound handling (conditional render in SWDB)
    inbound_status,

    -- Attachment indicator
    attachment_count

FROM invoices
WHERE deleted_at IS NULL;


-- ============================================================================
-- POSTGRESQL ACCESS CONTROL (not applicable to SQLite)
--
-- Execute these statements after schema creation on PostgreSQL deployments.
-- SQLite enforcement is handled in SDK application code.
--
-- Roles assumed:
--   sdk_role  — Float SDK database user (single-tenant, one Float per tenant)
--   core_role — Core service database user (full table ownership)
--   edge_role — Edge service database user (transmission contract)
-- ============================================================================

-- Revoke default PUBLIC access to base tables
-- REVOKE ALL ON invoices FROM PUBLIC;
-- REVOKE ALL ON invoice_line_items FROM PUBLIC;
-- REVOKE ALL ON invoice_references FROM PUBLIC;
-- REVOKE ALL ON invoice_tax_categories FROM PUBLIC;
-- REVOKE ALL ON invoice_attachments FROM PUBLIC;
-- REVOKE ALL ON invoice_transmission_attempts FROM PUBLIC;
-- REVOKE ALL ON invoice_allowance_charges FROM PUBLIC;
-- REVOKE ALL ON invoice_history FROM PUBLIC;

-- Revoke default PUBLIC access to views
-- REVOKE ALL ON vw_invoice_firs FROM PUBLIC;
-- REVOKE ALL ON vw_invoice_user_editable FROM PUBLIC;
-- REVOKE ALL ON vw_invoice_system FROM PUBLIC;
-- REVOKE ALL ON vw_invoice_display FROM PUBLIC;
-- REVOKE ALL ON vw_invoices_summary FROM PUBLIC;
-- REVOKE ALL ON vw_invoice_metrics FROM PUBLIC;
-- REVOKE ALL ON vw_payment_variances FROM PUBLIC;

-- Core: full ownership of all tables
-- GRANT ALL PRIVILEGES ON invoices TO core_role;
-- GRANT ALL PRIVILEGES ON invoice_line_items TO core_role;
-- GRANT ALL PRIVILEGES ON invoice_references TO core_role;
-- GRANT ALL PRIVILEGES ON invoice_tax_categories TO core_role;
-- GRANT ALL PRIVILEGES ON invoice_attachments TO core_role;
-- GRANT ALL PRIVILEGES ON invoice_transmission_attempts TO core_role;
-- GRANT ALL PRIVILEGES ON invoice_allowance_charges TO core_role;
-- GRANT ALL PRIVILEGES ON invoice_history TO core_role;

-- Edge: read all, write transmission fields through controlled contract
-- GRANT SELECT ON invoices TO edge_role;
-- GRANT UPDATE (transmission_status, transmission_status_error,
--               sign_date, transmission_date, acknowledgement_date,
--               csid, csid_status, firs_confirmation, firs_response_data,
--               qr_code_data, workflow_status,
--               retry_count, last_retry_at, next_retry_at,
--               updated_at) ON invoices TO edge_role;
-- GRANT SELECT ON vw_invoice_firs TO edge_role;
-- GRANT SELECT ON vw_invoice_system TO edge_role;
-- GRANT INSERT ON invoice_transmission_attempts TO edge_role;

-- SDK: read views, limited UPDATE on user-editable fields
-- GRANT SELECT ON vw_invoice_firs TO sdk_role;
-- GRANT SELECT ON vw_invoice_system TO sdk_role;
-- GRANT SELECT ON vw_invoice_display TO sdk_role;
-- GRANT SELECT ON vw_invoice_user_editable TO sdk_role;
-- GRANT SELECT ON vw_invoices_summary TO sdk_role;
-- GRANT SELECT ON vw_invoice_metrics TO sdk_role;
-- GRANT SELECT ON vw_payment_variances TO sdk_role;
-- GRANT UPDATE (payment_status, inbound_status,
--               inbound_action_at, inbound_action_by_user_id,
--               inbound_action_by_user_email, inbound_action_reason)
--   ON invoices TO sdk_role;

-- Row-level security for tenant isolation (PostgreSQL 9.5+)
-- ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY tenant_isolation ON invoices
--   USING (company_id = current_setting('app.company_id', true));
-- (Session setup: SET app.company_id = 'TENANT_XYZ';)


-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
