"""
WS7: Audit Trail Report Generator — PDF

Content: Complete edit history — who changed what, when, before/after values.
Date filter: audit event created_at
"""

from __future__ import annotations

import json
from datetime import date
from typing import Any

import structlog
from psycopg_pool import AsyncConnectionPool

from src.reports.pdf_renderer import render_pdf
from src.reports.statistics_service import resolve_period
from src.reports.models import StatisticsPeriod

logger = structlog.get_logger()

CONTENT_TYPE = "application/pdf"

_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; font-size: 10px; }}
    h1 {{ color: #003366; border-bottom: 3px solid #003366; padding-bottom: 10px; font-size: 20px; }}
    h2 {{ color: #003366; margin-top: 25px; font-size: 14px; }}
    .summary {{ display: flex; gap: 30px; margin: 15px 0; }}
    .summary-item {{ background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 6px; padding: 12px 20px; }}
    .summary-value {{ font-size: 1.5em; font-weight: bold; color: #003366; }}
    table {{ width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 9px; }}
    th {{ background: #003366; color: white; padding: 8px; text-align: left; font-size: 9px; }}
    td {{ padding: 6px 8px; border-bottom: 1px solid #dee2e6; word-break: break-word; }}
    tr:nth-child(even) {{ background: #f2f2f2; }}
    .action-create {{ color: #28a745; font-weight: bold; }}
    .action-update {{ color: #0563c1; font-weight: bold; }}
    .action-delete {{ color: #dc3545; font-weight: bold; }}
    .changes {{ font-size: 8px; color: #666; max-width: 300px; }}
    .footer {{ margin-top: 30px; font-size: 8px; color: #999; border-top: 1px solid #ddd; padding-top: 8px; }}
</style>
</head>
<body>
    <h1>Audit Trail Report</h1>
    <p><strong>Period:</strong> {date_from} to {date_to}</p>
    <p><strong>Company:</strong> {company_id}</p>

    <div class="summary">
        <div class="summary-item">
            <div class="summary-value">{total_events}</div>
            <div>Total Events</div>
        </div>
        <div class="summary-item">
            <div class="summary-value">{unique_actors}</div>
            <div>Unique Users</div>
        </div>
    </div>

    <h2>Event Breakdown by Action</h2>
    {action_table}

    <h2>Audit Events</h2>
    {events_table}

    <div class="footer">
        Generated by Helium Core Service &mdash; WS7 Report Engine
    </div>
</body>
</html>
"""


def _action_class(action: str) -> str:
    action_upper = (action or "").upper()
    if action_upper == "CREATE":
        return "action-create"
    elif action_upper in ("UPDATE", "FINALIZE"):
        return "action-update"
    elif action_upper == "DELETE":
        return "action-delete"
    return ""


def _truncate(value: Any, max_len: int = 100) -> str:
    s = str(value) if value else "-"
    return s[:max_len] + "..." if len(s) > max_len else s


async def generate(
    pool: AsyncConnectionPool,
    filters: dict[str, Any],
    company_id: str,
) -> tuple[bytes, str]:
    """Generate audit trail report PDF. Returns (bytes, content_type)."""
    date_from = filters.get("date_from")
    date_to = filters.get("date_to")

    if date_from:
        date_from = date.fromisoformat(str(date_from))
    if date_to:
        date_to = date.fromisoformat(str(date_to))

    d_from, d_to = resolve_period(StatisticsPeriod.MONTH, date_from, date_to)

    where_parts = ["created_at::DATE >= %s::DATE", "created_at::DATE <= %s::DATE"]
    params: list[Any] = [str(d_from), str(d_to)]

    if company_id and company_id != "default":
        where_parts.append("company_id = %s")
        params.append(company_id)

    where_clause = " AND ".join(where_parts)

    async with pool.connection() as conn:
        await conn.execute("SET search_path TO notifications")

        # Fetch audit events
        cur = await conn.execute(
            f"""
            SELECT
                audit_id, event_type, entity_type, entity_id,
                action, actor_id, changed_fields, metadata,
                created_at
            FROM audit_log
            WHERE {where_clause}
            ORDER BY created_at DESC
            LIMIT 5000
            """,
            params,
        )
        rows = await cur.fetchall()
        col_names = [desc.name for desc in cur.description]

        # Action breakdown
        cur = await conn.execute(
            f"""
            SELECT action, COUNT(*)
            FROM audit_log
            WHERE {where_clause}
            GROUP BY action ORDER BY COUNT(*) DESC
            """,
            params,
        )
        action_breakdown = await cur.fetchall()

    events = [dict(zip(col_names, r)) for r in rows]
    unique_actors = len(set(e.get("actor_id") or "system" for e in events))

    # Build action breakdown table
    action_rows = ""
    for action, count in action_breakdown:
        cls = _action_class(action)
        action_rows += f'<tr><td class="{cls}">{action}</td><td>{count}</td></tr>\n'
    action_table = (
        f"<table><tr><th>Action</th><th>Count</th></tr>{action_rows}</table>"
        if action_rows
        else "<p>No audit events in this period.</p>"
    )

    # Build events table
    event_rows = ""
    for e in events:
        created = e.get("created_at")
        ts = created.strftime("%Y-%m-%d %H:%M") if created else "-"
        cls = _action_class(e.get("action", ""))
        changed = e.get("changed_fields")
        if isinstance(changed, list):
            changed_str = ", ".join(changed[:10])
        elif changed:
            changed_str = _truncate(changed)
        else:
            changed_str = "-"

        event_rows += (
            f"<tr>"
            f"<td>{ts}</td>"
            f'<td class="{cls}">{e.get("action", "-")}</td>'
            f"<td>{e.get('entity_type', '-')}</td>"
            f"<td>{_truncate(e.get('entity_id'), 20)}</td>"
            f"<td>{e.get('actor_id') or 'system'}</td>"
            f'<td class="changes">{changed_str}</td>'
            f"</tr>\n"
        )

    events_table = (
        f"<table>"
        f"<tr><th>Time</th><th>Action</th><th>Entity</th>"
        f"<th>Entity ID</th><th>Actor</th><th>Changed Fields</th></tr>"
        f"{event_rows}</table>"
        if event_rows
        else "<p>No audit events in this period.</p>"
    )

    html = _TEMPLATE.format(
        date_from=str(d_from),
        date_to=str(d_to),
        company_id=company_id,
        total_events=len(events),
        unique_actors=unique_actors,
        action_table=action_table,
        events_table=events_table,
    )

    pdf_bytes = render_pdf(html)
    logger.info(
        "audit_trail_report_generated",
        company_id=company_id,
        event_count=len(events),
        size=len(pdf_bytes),
    )
    return pdf_bytes, CONTENT_TYPE
