"""
WS7: Compliance Report Generator — PDF

Content: FIRS compliance scorecard — acceptance rate, rejection analysis,
common rejection reasons, monthly compliance trend, overdue count.

Date filter: issue_date
"""

from __future__ import annotations

from datetime import date
from typing import Any

import structlog
from psycopg_pool import AsyncConnectionPool

from src.reports.pdf_renderer import render_pdf
from src.reports.statistics_service import _compliance, resolve_period
from src.reports.models import StatisticsPeriod

logger = structlog.get_logger()

CONTENT_TYPE = "application/pdf"

_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; }}
    h1 {{ color: #003366; border-bottom: 3px solid #003366; padding-bottom: 10px; }}
    h2 {{ color: #003366; margin-top: 30px; }}
    .summary-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 20px 0; }}
    .metric-card {{ background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 20px; text-align: center; }}
    .metric-value {{ font-size: 2em; font-weight: bold; color: #003366; }}
    .metric-label {{ font-size: 0.9em; color: #666; margin-top: 5px; }}
    table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
    th {{ background: #003366; color: white; padding: 10px; text-align: left; }}
    td {{ padding: 8px 10px; border-bottom: 1px solid #dee2e6; }}
    tr:nth-child(even) {{ background: #f2f2f2; }}
    .footer {{ margin-top: 40px; font-size: 0.8em; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }}
    .score-good {{ color: #28a745; }}
    .score-fair {{ color: #ffc107; }}
    .score-poor {{ color: #dc3545; }}
</style>
</head>
<body>
    <h1>Compliance Report</h1>
    <p><strong>Period:</strong> {date_from} to {date_to}</p>
    <p><strong>Company:</strong> {company_id}</p>

    <div class="summary-grid">
        <div class="metric-card">
            <div class="metric-value {acceptance_class}">{acceptance_rate}%</div>
            <div class="metric-label">FIRS Acceptance Rate</div>
        </div>
        <div class="metric-card">
            <div class="metric-value">{submitted_count}</div>
            <div class="metric-label">Submitted to FIRS</div>
        </div>
        <div class="metric-card">
            <div class="metric-value">{accepted_count}</div>
            <div class="metric-label">Accepted</div>
        </div>
        <div class="metric-card">
            <div class="metric-value">{rejected_count}</div>
            <div class="metric-label">Rejected</div>
        </div>
        <div class="metric-card">
            <div class="metric-value">{overdue_count}</div>
            <div class="metric-label">Overdue Invoices</div>
        </div>
        <div class="metric-card">
            <div class="metric-value">{disputed_count}</div>
            <div class="metric-label">Disputed</div>
        </div>
    </div>

    <h2>Common Rejection Reasons</h2>
    {rejection_table}

    <h2>Monthly Compliance Trend</h2>
    {trend_table}

    <div class="footer">
        Generated by Helium Core Service &mdash; WS7 Report Engine
    </div>
</body>
</html>
"""


def _score_class(rate: float) -> str:
    if rate >= 90:
        return "score-good"
    elif rate >= 70:
        return "score-fair"
    return "score-poor"


def _build_rejection_table(reasons: list[dict]) -> str:
    if not reasons:
        return "<p>No rejections in this period.</p>"
    rows = ""
    for r in reasons:
        rows += f"<tr><td>{r['reason']}</td><td>{r['count']}</td></tr>\n"
    return f"<table><tr><th>Reason</th><th>Count</th></tr>{rows}</table>"


def _build_trend_table(trend: list[dict]) -> str:
    if not trend:
        return "<p>No data available for trend.</p>"
    rows = ""
    for t in trend:
        cls = _score_class(t["score"])
        rows += f'<tr><td>{t["month"]}</td><td class="{cls}">{t["score"]}%</td></tr>\n'
    return f"<table><tr><th>Month</th><th>Score</th></tr>{rows}</table>"


async def generate(
    pool: AsyncConnectionPool,
    filters: dict[str, Any],
    company_id: str,
) -> tuple[bytes, str]:
    """Generate compliance report PDF. Returns (bytes, content_type)."""
    date_from = filters.get("date_from")
    date_to = filters.get("date_to")

    if date_from:
        date_from = date.fromisoformat(str(date_from))
    if date_to:
        date_to = date.fromisoformat(str(date_to))

    d_from, d_to = resolve_period(StatisticsPeriod.MONTH, date_from, date_to)

    data = await _compliance(pool, d_from, d_to, company_id)

    acceptance_rate = data.get("firs_acceptance_rate", 0)
    html = _TEMPLATE.format(
        date_from=str(d_from),
        date_to=str(d_to),
        company_id=company_id,
        acceptance_rate=acceptance_rate,
        acceptance_class=_score_class(acceptance_rate),
        submitted_count=data.get("submitted_count", 0),
        accepted_count=data.get("accepted_count", 0),
        rejected_count=data.get("rejected_count", 0),
        overdue_count=data.get("overdue_count", 0),
        disputed_count=data.get("disputed_count", 0),
        rejection_table=_build_rejection_table(data.get("common_rejection_reasons", [])),
        trend_table=_build_trend_table(data.get("monthly_trend", [])),
    )

    pdf_bytes = render_pdf(html)
    logger.info("compliance_report_generated", company_id=company_id, size=len(pdf_bytes))
    return pdf_bytes, CONTENT_TYPE
