"""
WS7: Monthly Summary Report Generator — PDF

Content: Monthly rollup — invoice volumes, total values, tax collected,
top customers, compliance trend.

Date filter: issue_date
"""

from __future__ import annotations

from datetime import date
from typing import Any

import structlog
from psycopg_pool import AsyncConnectionPool

from src.reports.pdf_renderer import render_pdf
from src.reports.statistics_service import (
    _compliance,
    _invoices,
    _overview,
    resolve_period,
)
from src.reports.models import StatisticsPeriod

logger = structlog.get_logger()

CONTENT_TYPE = "application/pdf"

_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; }}
    h1 {{ color: #003366; border-bottom: 3px solid #003366; padding-bottom: 10px; }}
    h2 {{ color: #003366; margin-top: 30px; }}
    .summary-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin: 20px 0; }}
    .metric-card {{ background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; text-align: center; }}
    .metric-value {{ font-size: 1.6em; font-weight: bold; color: #003366; }}
    .metric-label {{ font-size: 0.85em; color: #666; margin-top: 4px; }}
    table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
    th {{ background: #003366; color: white; padding: 10px; text-align: left; }}
    td {{ padding: 8px 10px; border-bottom: 1px solid #dee2e6; }}
    tr:nth-child(even) {{ background: #f2f2f2; }}
    .amount {{ text-align: right; font-family: 'Consolas', monospace; }}
    .footer {{ margin-top: 40px; font-size: 0.8em; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }}
</style>
</head>
<body>
    <h1>Monthly Summary Report</h1>
    <p><strong>Period:</strong> {date_from} to {date_to}</p>
    <p><strong>Company:</strong> {company_id}</p>

    <div class="summary-grid">
        <div class="metric-card">
            <div class="metric-value">{total_invoices}</div>
            <div class="metric-label">Total Invoices</div>
        </div>
        <div class="metric-card">
            <div class="metric-value">\u20a6{total_value}</div>
            <div class="metric-label">Total Value</div>
        </div>
        <div class="metric-card">
            <div class="metric-value">\u20a6{total_tax}</div>
            <div class="metric-label">Tax Collected</div>
        </div>
        <div class="metric-card">
            <div class="metric-value">{acceptance_rate}%</div>
            <div class="metric-label">FIRS Acceptance</div>
        </div>
    </div>

    <h2>Invoice Breakdown</h2>

    <h3>By Status</h3>
    {status_table}

    <h3>By Direction</h3>
    {direction_table}

    <h3>Payment Health</h3>
    {payment_table}

    <h2>Compliance</h2>
    <p>Acceptance Rate: <strong>{acceptance_rate}%</strong> &mdash;
       Submitted: {submitted_count}, Accepted: {accepted_count}, Rejected: {rejected_count}</p>

    {rejection_table}

    <div class="footer">
        Generated by Helium Core Service &mdash; WS7 Report Engine
    </div>
</body>
</html>
"""


def _fmt_amount(val: float) -> str:
    return f"{val:,.2f}"


def _dict_table(data: dict, header1: str = "Category", header2: str = "Count") -> str:
    if not data:
        return "<p>No data.</p>"
    rows = "".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in data.items())
    return f"<table><tr><th>{header1}</th><th>{header2}</th></tr>{rows}</table>"


async def generate(
    pool: AsyncConnectionPool,
    filters: dict[str, Any],
    company_id: str,
) -> tuple[bytes, str]:
    """Generate monthly summary report PDF. Returns (bytes, content_type)."""
    date_from = filters.get("date_from")
    date_to = filters.get("date_to")

    if date_from:
        date_from = date.fromisoformat(str(date_from))
    if date_to:
        date_to = date.fromisoformat(str(date_to))

    d_from, d_to = resolve_period(StatisticsPeriod.MONTH, date_from, date_to)

    # Gather data from multiple section handlers
    overview = await _overview(pool, d_from, d_to, company_id)
    invoice_data = await _invoices(pool, d_from, d_to, company_id)
    compliance = await _compliance(pool, d_from, d_to, company_id)

    # Rejection reasons
    reasons = compliance.get("common_rejection_reasons", [])
    if reasons:
        reason_rows = "".join(
            f"<tr><td>{r['reason']}</td><td>{r['count']}</td></tr>"
            for r in reasons
        )
        rejection_table = (
            f"<table><tr><th>Rejection Reason</th><th>Count</th></tr>"
            f"{reason_rows}</table>"
        )
    else:
        rejection_table = "<p>No rejections in this period.</p>"

    html = _TEMPLATE.format(
        date_from=str(d_from),
        date_to=str(d_to),
        company_id=company_id,
        total_invoices=overview.get("total_invoices", 0),
        total_value=_fmt_amount(overview.get("total_value", 0)),
        total_tax=_fmt_amount(overview.get("total_tax", 0)),
        acceptance_rate=compliance.get("firs_acceptance_rate", 0),
        submitted_count=compliance.get("submitted_count", 0),
        accepted_count=compliance.get("accepted_count", 0),
        rejected_count=compliance.get("rejected_count", 0),
        status_table=_dict_table(invoice_data.get("by_status", {}), "Workflow Status", "Count"),
        direction_table=_dict_table(invoice_data.get("by_direction", {}), "Direction", "Count"),
        payment_table=_dict_table(invoice_data.get("payment_health", {}), "Payment Status", "Count"),
        rejection_table=rejection_table,
    )

    pdf_bytes = render_pdf(html)
    logger.info(
        "monthly_summary_report_generated",
        company_id=company_id,
        size=len(pdf_bytes),
    )
    return pdf_bytes, CONTENT_TYPE
