"""
Ingestion Pipeline

Shared 7-step pipeline used by both bulk (Float) and external (API) flows.
Each step is explicit and auditable. Step 4 (blob write) is the COMMIT POINT:
steps 1-3 can fail cleanly, steps 5-7 are best-effort after commit.

Pipeline:
    1. validate_files()         — file count, extension, size checks
    2. check_daily_limit()      — per-company quota via HeartBeat
    3. dedup_check()            — per-file SHA256, two-level: session cache → HeartBeat
    4. write_blobs() ★          — COMMIT POINT: one POST /api/blobs/write per file
    5. enqueue_core()           — Core processing queue (orphan blob recovery exists)
    6. register_blobs()         — HeartBeat metadata (fire-and-forget)
    7. audit_log()              — Immutable audit trail (fire-and-forget)

Identity model:
    data_uuid        — Per-request group (always generated, even single file).
                       Maps to HeartBeat's source_document_id on blob_batches.
    blob_uuid        — Per-file storage ID (one per file, generated by Relay).
                       Maps to HeartBeat's file_entries.blob_uuid.
                       Exposed to SDK as file_uuid in the API response.
    file_display_id  — SDK-generated per-file PK (from metadata.file_display_ids[]).
                       Forwarded to HeartBeat as file_entries.file_display_id.
    batch_display_id — SDK-generated batch PK (from metadata.batch_display_id).
                       Forwarded to HeartBeat as blob_batches.batch_display_id.
"""

import logging
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from helium_hash import sha256_file
from uuid6 import uuid7

from ..config import RelayConfig
from ..core.dedup import DedupChecker
from ..core.validation import validate_files
from ..db.ledger import IngestLedger
from ..errors import (
    DuplicateFileError,
    JWTRejectedError,
    RateLimitExceededError,
    InternalError,
)

logger = logging.getLogger(__name__)


@dataclass
class IngestResult:
    """Result of the ingestion pipeline.

    Identity model:
        data_uuid  — Per-request group (always present, even single file)
        blob_uuids — Per-file HeartBeat storage IDs (exposed as file_uuids in API)
    """

    data_uuid: str
    queue_id: str
    filenames: List[str]
    file_count: int
    total_size_bytes: int

    # Per-file results (one entry per uploaded file)
    file_hashes: List[str] = field(default_factory=list)
    blob_uuids: List[str] = field(default_factory=list)
    blob_paths: List[str] = field(default_factory=list)

    status: str = "ingested"

    @property
    def file_hash(self) -> str:
        """Primary file hash (first file, for backward compat)."""
        return self.file_hashes[0] if self.file_hashes else ""

    @property
    def blob_path(self) -> str:
        """Primary blob path (first file, for backward compat)."""
        return self.blob_paths[0] if self.blob_paths else ""

    def to_payload(self) -> Dict[str, Any]:
        """Serializable envelope for the ingest ledger's idempotent-replay store."""
        return asdict(self)

    @classmethod
    def from_payload(cls, payload: Dict[str, Any]) -> "IngestResult":
        """Reconstruct an IngestResult from a ledger ``result_json`` payload.

        Tolerant of unknown keys (forward-compat if the dataclass shrinks);
        only the declared fields are pulled through.
        """
        fields = {f.name for f in cls.__dataclass_fields__.values()}  # type: ignore[attr-defined]
        return cls(**{k: v for k, v in payload.items() if k in fields})


class IngestionService:
    """
    Shared ingestion pipeline for bulk and external flows.

    Usage:
        service = IngestionService(config, heartbeat, core)
        result = await service.ingest(files, api_key, trace_id)
    """

    def __init__(
        self,
        config: RelayConfig,
        heartbeat_client: Any,
        core_client: Any,
        redis_client: Any = None,
        ledger: Optional[IngestLedger] = None,
    ):
        self._config = config
        self._heartbeat = heartbeat_client
        self._core = core_client
        self._redis = redis_client
        # Durable write-first ingest ledger (relay.db). Optional/guarded:
        # when None (RELAY_DB_PATH unset) the ledger is disabled and the
        # pipeline behaves exactly as before — no crash-survival, no durable
        # idempotency, zero behaviour change. Q28 / Frontdoor §3.2.
        self._ledger = ledger

    async def ingest(
        self,
        files: List[Tuple[str, bytes]],
        api_key: str,
        trace_id: str = "",
        metadata: Optional[Dict] = None,
        jwt_token: Optional[str] = None,
        tenant_id: Optional[str] = None,
    ) -> IngestResult:
        """
        Run the full 7-step ingestion pipeline.

        Per-file model: each file is hashed, dedup-checked, and uploaded
        individually. All requests (single or multi-file) get a data_uuid.

        Write-first durable ledger (Q28 / Frontdoor §3.2): when the ingest
        ledger is enabled (RELAY_DB_PATH set), a ``relay.db`` row is written
        BEFORE the Step 4 blob commit (crash-survival), and the idempotency
        key ``(tenant_id, file_sha256)`` short-circuits a re-ingest of the
        same bytes to the prior result (idempotent replay; pipeline not re-run).
        When the ledger is disabled this is a no-op.

        Args:
            files: List of (filename, file_data) tuples.
            api_key: Authenticated API key (from auth middleware).
            trace_id: Request trace ID for logging.
            metadata: SDK identity/trace fields (forwarded to HeartBeat).
            jwt_token: Bearer JWT (forwarded to HeartBeat/Core for identity).
            tenant_id: Tenant slug for the ledger idempotency key. Defaults to
                ``api_key`` when not supplied (the api_key is the tenant
                identifier on the current single-binary deployment shape).

        Returns:
            IngestResult with per-file hashes, blob_uuids, blob_paths.

        Raises:
            ValidationFailedError: Steps 1 validation failure.
            RateLimitExceededError: Step 2 daily limit exceeded.
            DuplicateFileError: Step 3 duplicate detected.
            JWTRejectedError: HeartBeat returns 401 on blob write.
            InternalError: Step 4+ critical failure.
        """
        # Tenant for the ledger idempotency key. On today's single-binary
        # shape the api_key resolves the tenant (deps.py::_tenant_id_for_api_key),
        # so it is the safe default when an explicit tenant slug is not passed.
        ledger_tenant = tenant_id or api_key
        # ── Step 1: Validate files ────────────────────────────────────────
        validate_files(files, self._config)
        logger.info(
            f"[{trace_id}] Step 1/7: Validation passed — {len(files)} files"
        )

        # ── Step 2: Check daily limit ─────────────────────────────────────
        await self._check_daily_limit(api_key, len(files), trace_id)
        logger.info(f"[{trace_id}] Step 2/7: Daily limit OK")

        # ── Step 3: Per-file dedup check ──────────────────────────────────
        dedup = DedupChecker(self._heartbeat, trace_id=trace_id)
        per_file_hashes: List[str] = []

        for filename, file_data in files:
            # CSSV1 S4 (R7): canonical SHA-256 via helium_hash. Same
            # primitive as HB / Float SDK / Reader/Scout SDK.
            file_hash = sha256_file(file_data)
            per_file_hashes.append(file_hash)

            dedup_result = await dedup.check(file_data)

            if dedup_result.is_duplicate:
                raise DuplicateFileError(
                    file_hash=dedup_result.file_hash,
                    original_queue_id=dedup_result.original_queue_id,
                )

        logger.info(
            f"[{trace_id}] Step 3/7: Dedup passed — "
            f"{len(files)} files checked"
        )

        # Generate identifiers
        # data_uuid: always generated (even single file) — per-request group
        data_uuid = str(uuid7())
        filenames = [name for name, _ in files]
        total_size = sum(len(data) for _, data in files)

        # ── Write-first: durable ledger record (Q28 / Frontdoor §3.2) ─────
        # Idempotency key = (tenant_id, file_sha256). The request's sha is the
        # primary (first) file's canonical hash — for the single-file external
        # / Path-A case this IS the file. Written BEFORE the Step 4 commit so a
        # crash mid-pipeline leaves a durable trace; a re-ingest of the same
        # bytes short-circuits to the prior result (idempotent replay).
        ledger_sha = per_file_hashes[0] if per_file_hashes else ""
        if self._ledger is not None and ledger_sha:
            outcome, prior = self._ledger.record_received(
                ledger_tenant, ledger_sha,
                trace_id=trace_id, data_uuid=data_uuid,
            )
            if outcome == "duplicate":
                replay = prior.result_payload if prior is not None else None
                if replay is not None:
                    logger.info(
                        f"[{trace_id}] Ledger idempotent replay — "
                        f"tenant={ledger_tenant}, sha={ledger_sha[:12]}... "
                        f"(pipeline NOT re-run)"
                    )
                    result = IngestResult.from_payload(replay)
                    result.status = "duplicate"
                    return result
                # Row exists but no replay payload (e.g. a prior crash left it
                # 'pending', or a prior 'error'). Surface as a duplicate rather
                # than silently re-processing — the durable key already saw it.
                raise DuplicateFileError(file_hash=ledger_sha)

        # ── Step 4: COMMIT POINT — Write blobs (one per file) ─────────────
        blob_uuids: List[str] = []
        blob_paths: List[str] = []

        # Extract SDK canonical display IDs from metadata (if present)
        file_display_ids = (metadata or {}).get("file_display_ids", [])
        batch_display_id = (metadata or {}).get("batch_display_id", "")

        for i, (filename, file_data) in enumerate(files):
            blob_uuid = str(uuid7())
            blob_uuids.append(blob_uuid)

            # Enrich per-file metadata with canonical display IDs
            per_file_metadata = dict(metadata) if metadata else {}
            # Remove the array — each file gets its own display_id
            per_file_metadata.pop("file_display_ids", None)
            if i < len(file_display_ids):
                per_file_metadata["file_display_id"] = file_display_ids[i]
            if batch_display_id:
                per_file_metadata["batch_display_id"] = batch_display_id
            # source_document_id = Relay's data_uuid (per-request tracking)
            per_file_metadata["source_document_id"] = data_uuid

            try:
                blob_result = await self._heartbeat.write_blob(
                    blob_uuid=blob_uuid,
                    filename=filename,
                    file_data=file_data,
                    metadata=per_file_metadata,
                    jwt_token=jwt_token,
                )
            except JWTRejectedError as e:
                # Let JWT rejection propagate cleanly as 401 — but record the
                # terminal failure in the durable ledger first.
                self._ledger_mark_error(ledger_tenant, ledger_sha, str(e))
                raise
            except Exception as e:
                self._ledger_mark_error(
                    ledger_tenant, ledger_sha,
                    f"Blob write failed for {filename}: {e}",
                )
                raise InternalError(
                    message=f"Blob write failed for {filename}: {e}",
                    original_error=e,
                ) from e

            blob_paths.append(blob_result.get("blob_path", ""))
            logger.debug(
                f"[{trace_id}] Step 4/7: Blob {i+1}/{len(files)} written — "
                f"uuid={blob_uuid}, file={filename}"
            )

        logger.info(
            f"[{trace_id}] Step 4/7: All blobs written — "
            f"{len(files)} files, data_uuid={data_uuid}"
        )

        # Record dedup hashes after successful commit (session cache only).
        #
        # CSSV1 S4 (R7): the Level-2 HeartBeat persistent record path was
        # deleted in this chip. Authoritative dedup state now flows
        # through HB's own /api/blobs/register handler (D2) which writes
        # `blob.blob_deduplication` rows as a side effect of the blob
        # commit at Step 4. Relay no longer makes a separate
        # /api/dedup/record call — that was an outbound chip from the
        # pre-CSSV1 design and is now redundant.
        #
        # Session cache (Level 1) stays — it catches in-request
        # duplicates without an HB round-trip per file.
        for file_hash in per_file_hashes:
            dedup.record(file_hash)

        # ── Step 5: Enqueue Core (best-effort) ────────────────────────────
        queue_id = await self._enqueue_core(
            data_uuid, filenames, total_size, trace_id,
            metadata=metadata, jwt_token=jwt_token,
        )
        logger.info(
            f"[{trace_id}] Step 5/7: Core enqueued — queue_id={queue_id}"
        )

        # ── Step 6: Register blobs (fire-and-forget) ──────────────────────
        for i, (filename, file_data) in enumerate(files):
            await self._register_blob(
                blob_uuids[i], filename, len(file_data),
                per_file_hashes[i], api_key, trace_id,
                data_uuid=data_uuid,
                file_index=i,
                metadata=metadata, jwt_token=jwt_token,
            )
        logger.info(f"[{trace_id}] Step 6/7: Blobs registered")

        # ── Step 7: Audit log (fire-and-forget) ───────────────────────────
        await self._audit_log(
            data_uuid, queue_id, filenames, api_key, trace_id,
            metadata=metadata,
        )
        logger.info(f"[{trace_id}] Step 7/7: Audit logged")

        result = IngestResult(
            data_uuid=data_uuid,
            queue_id=queue_id,
            filenames=filenames,
            file_count=len(files),
            total_size_bytes=total_size,
            file_hashes=per_file_hashes,
            blob_uuids=blob_uuids,
            blob_paths=blob_paths,
        )

        # Write-first ledger: pipeline succeeded → mark processed + store the
        # result envelope so a future re-ingest of the same bytes replays it.
        if self._ledger is not None and ledger_sha:
            self._ledger.mark_processed(
                ledger_tenant, ledger_sha,
                data_uuid=data_uuid,
                result_payload=result.to_payload(),
            )

        return result

    # ── Internal Helpers ──────────────────────────────────────────────────

    def _ledger_mark_error(
        self, tenant_id: str, file_sha256: str, message: str
    ) -> None:
        """Best-effort ledger error mark; never raises (ledger must not mask
        the real pipeline error). No-op when the ledger is disabled."""
        if self._ledger is None or not file_sha256:
            return
        try:
            self._ledger.mark_error(tenant_id, file_sha256, message)
        except Exception as e:  # pragma: no cover - defensive
            logger.warning(f"ingest_ledger mark_error failed: {e}")

    async def _check_daily_limit(
        self, api_key: str, file_count: int, trace_id: str
    ) -> None:
        """
        Step 2: Check daily upload limit.

        Priority: Redis (primary) -> HeartBeat (fallback) -> allow (degraded).
        """
        # Primary: Redis rate limiting
        if self._redis is not None and self._redis.is_available:
            try:
                result = await self._redis.check_rate_limit(
                    company_id=api_key,
                    file_count=file_count,
                )
                if not result.allowed:
                    raise RateLimitExceededError(
                        message=(
                            f"Daily upload limit reached. "
                            f"Limit: {result.limit}, remaining: {result.remaining}."
                        )
                    )
                return  # Redis check passed
            except RateLimitExceededError:
                raise
            except Exception as e:
                logger.warning(
                    f"[{trace_id}] Redis rate limit failed — falling back to HeartBeat: {e}"
                )

        # Fallback: HeartBeat
        try:
            result = await self._heartbeat.check_daily_limit(
                company_id=api_key,
                file_count=file_count,
            )
            if result.get("limit_reached"):
                remaining = result.get("remaining", 0)
                daily_limit = result.get("daily_limit", 0)
                raise RateLimitExceededError(
                    message=(
                        f"Daily upload limit reached. "
                        f"Limit: {daily_limit}, remaining: {remaining}."
                    )
                )
        except RateLimitExceededError:
            raise
        except Exception as e:
            # Graceful degradation: if both Redis and HeartBeat are down, allow
            logger.warning(
                f"[{trace_id}] Daily limit check failed — allowing: {e}"
            )

    async def _enqueue_core(
        self,
        data_uuid: str,
        filenames: List[str],
        file_size_bytes: int,
        trace_id: str,
        metadata: Optional[Dict] = None,
        jwt_token: Optional[str] = None,
    ) -> str:
        """Step 5: Enqueue file for Core processing (best-effort).

        Forwards JWT so Core can identify the user. Metadata is included
        for Core's own traceability records.
        """
        try:
            result = await self._core.enqueue(
                blob_uuid=data_uuid,
                filename=filenames[0] if len(filenames) == 1 else ",".join(filenames),
                file_size_bytes=file_size_bytes,
                batch_id=trace_id,
                metadata=metadata,
                jwt_token=jwt_token,
            )
            return result["queue_id"]
        except Exception as e:
            # Best-effort: orphaned blob will be reconciled by HeartBeat
            logger.warning(
                f"[{trace_id}] Core enqueue failed — blob is orphaned: {e}"
            )
            return f"orphan_{data_uuid}"

    async def _register_blob(
        self,
        blob_uuid: str,
        filename: str,
        file_size_bytes: int,
        file_hash: str,
        api_key: str,
        trace_id: str,
        data_uuid: str = "",
        file_index: int = 0,
        metadata: Optional[Dict] = None,
        jwt_token: Optional[str] = None,
    ) -> None:
        """Step 6: Register blob metadata in HeartBeat (fire-and-forget).

        Forwards metadata so HeartBeat stamps file_entries with identity/trace.
        Enriches metadata with per-file file_display_id and batch-level
        batch_display_id + source_document_id for canonical dual identity.
        JWT allows HeartBeat to verify the user identity.
        """
        # Enrich metadata with canonical display IDs
        enriched_metadata = dict(metadata) if metadata else {}

        # Map SDK's per-file display IDs (sent as array in metadata)
        file_display_ids = enriched_metadata.pop("file_display_ids", [])
        if file_index < len(file_display_ids):
            enriched_metadata["file_display_id"] = file_display_ids[file_index]

        # source_document_id = Relay's data_uuid (per-request tracking ID)
        if data_uuid:
            enriched_metadata["source_document_id"] = data_uuid

        # L30 §5 (DATA_MODEL_CANONICAL): surface external-supplied transaction_ids
        # as a first-class field so HB's registration worker seeds one
        # blob.file_transactions row per id (status='pending'). The external
        # batch path stamps metadata["transaction_id"] (one record = one file =
        # one transaction); a future N-per-file path may carry "transaction_ids".
        # Internal uploads carry neither → None → HB seeds nothing (Core creates
        # the rows at extraction).
        transaction_ids = enriched_metadata.get("transaction_ids")
        if not transaction_ids:
            single_txn = enriched_metadata.get("transaction_id")
            transaction_ids = [single_txn] if single_txn else None

        try:
            await self._heartbeat.register_blob(
                blob_uuid=blob_uuid,
                filename=filename,
                file_size_bytes=file_size_bytes,
                file_hash=file_hash,
                api_key=api_key,
                metadata=enriched_metadata,
                jwt_token=jwt_token,
                transaction_ids=transaction_ids,
            )
        except Exception as e:
            logger.warning(
                f"[{trace_id}] Blob registration failed (non-critical): {e}"
            )

    async def _audit_log(
        self,
        data_uuid: str,
        queue_id: str,
        filenames: List[str],
        api_key: str,
        trace_id: str,
        metadata: Optional[Dict] = None,
    ) -> None:
        """Step 7: Log audit event (fire-and-forget).

        Includes SDK metadata for audit trail (user_trace_id, machine_guid, etc.).
        """
        audit_details: Dict[str, Any] = {
            "data_uuid": data_uuid,
            "queue_id": queue_id,
            "filenames": filenames,
            "trace_id": trace_id,
        }
        # Merge SDK identity/trace into audit details
        if metadata:
            audit_details["sdk_metadata"] = metadata

        try:
            await self._heartbeat.audit_log(
                service="relay-api",
                event_type="file.ingested",
                user_id=metadata.get("helium_user_id", api_key) if metadata else api_key,
                details=audit_details,
            )
        except Exception as e:
            logger.warning(
                f"[{trace_id}] Audit log failed (non-critical): {e}"
            )
