"""
Ingestion Pipeline

Shared 7-step pipeline used by both bulk (Float) and external (API) flows.
Each step is explicit and auditable. Step 4 (blob write) is the COMMIT POINT:
steps 1-3 can fail cleanly, steps 5-7 are best-effort after commit.

Pipeline:
    1. validate_files()         — file count, extension, size checks
    2. check_daily_limit()      — per-company quota via HeartBeat
    3. dedup_check()            — per-file SHA256, two-level: session cache → HeartBeat
    4. write_blobs() ★          — COMMIT POINT: one POST /api/blobs/write per file
    5. enqueue_core()           — Core processing queue (orphan blob recovery exists)
    6. register_blobs()         — HeartBeat metadata (fire-and-forget)
    7. audit_log()              — Immutable audit trail (fire-and-forget)

Identity model:
    data_uuid        — Per-request group (always generated, even single file).
                       Maps to HeartBeat's source_document_id on blob_batches.
    blob_uuid        — Per-file storage ID (one per file, generated by Relay).
                       Maps to HeartBeat's file_entries.blob_uuid.
                       Exposed to SDK as file_uuid in the API response.
    file_display_id  — SDK-generated per-file PK (from metadata.file_display_ids[]).
                       Forwarded to HeartBeat as file_entries.file_display_id.
    batch_display_id — SDK-generated batch PK (from metadata.batch_display_id).
                       Forwarded to HeartBeat as blob_batches.batch_display_id.
"""

import hashlib
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from uuid6 import uuid7

from ..config import RelayConfig
from ..core.dedup import DedupChecker
from ..core.validation import validate_files
from ..errors import (
    DuplicateFileError,
    JWTRejectedError,
    RateLimitExceededError,
    InternalError,
)

logger = logging.getLogger(__name__)


@dataclass
class IngestResult:
    """Result of the ingestion pipeline.

    Identity model:
        data_uuid  — Per-request group (always present, even single file)
        blob_uuids — Per-file HeartBeat storage IDs (exposed as file_uuids in API)
    """

    data_uuid: str
    queue_id: str
    filenames: List[str]
    file_count: int
    total_size_bytes: int

    # Per-file results (one entry per uploaded file)
    file_hashes: List[str] = field(default_factory=list)
    blob_uuids: List[str] = field(default_factory=list)
    blob_paths: List[str] = field(default_factory=list)

    status: str = "ingested"

    @property
    def file_hash(self) -> str:
        """Primary file hash (first file, for backward compat)."""
        return self.file_hashes[0] if self.file_hashes else ""

    @property
    def blob_path(self) -> str:
        """Primary blob path (first file, for backward compat)."""
        return self.blob_paths[0] if self.blob_paths else ""


class IngestionService:
    """
    Shared ingestion pipeline for bulk and external flows.

    Usage:
        service = IngestionService(config, heartbeat, core)
        result = await service.ingest(files, api_key, trace_id)
    """

    def __init__(
        self,
        config: RelayConfig,
        heartbeat_client: Any,
        core_client: Any,
        redis_client: Any = None,
    ):
        self._config = config
        self._heartbeat = heartbeat_client
        self._core = core_client
        self._redis = redis_client

    async def ingest(
        self,
        files: List[Tuple[str, bytes]],
        api_key: str,
        trace_id: str = "",
        metadata: Optional[Dict] = None,
        jwt_token: Optional[str] = None,
    ) -> IngestResult:
        """
        Run the full 7-step ingestion pipeline.

        Per-file model: each file is hashed, dedup-checked, and uploaded
        individually. All requests (single or multi-file) get a data_uuid.

        Args:
            files: List of (filename, file_data) tuples.
            api_key: Authenticated API key (from auth middleware).
            trace_id: Request trace ID for logging.
            metadata: SDK identity/trace fields (forwarded to HeartBeat).
            jwt_token: Bearer JWT (forwarded to HeartBeat/Core for identity).

        Returns:
            IngestResult with per-file hashes, blob_uuids, blob_paths.

        Raises:
            ValidationFailedError: Steps 1 validation failure.
            RateLimitExceededError: Step 2 daily limit exceeded.
            DuplicateFileError: Step 3 duplicate detected.
            JWTRejectedError: HeartBeat returns 401 on blob write.
            InternalError: Step 4+ critical failure.
        """
        # ── Step 1: Validate files ────────────────────────────────────────
        validate_files(files, self._config)
        logger.info(
            f"[{trace_id}] Step 1/7: Validation passed — {len(files)} files"
        )

        # ── Step 2: Check daily limit ─────────────────────────────────────
        await self._check_daily_limit(api_key, len(files), trace_id)
        logger.info(f"[{trace_id}] Step 2/7: Daily limit OK")

        # ── Step 3: Per-file dedup check ──────────────────────────────────
        dedup = DedupChecker(self._heartbeat, trace_id=trace_id)
        per_file_hashes: List[str] = []

        for filename, file_data in files:
            file_hash = hashlib.sha256(file_data).hexdigest()
            per_file_hashes.append(file_hash)

            dedup_result = await dedup.check(file_data)

            if dedup_result.is_duplicate:
                raise DuplicateFileError(
                    file_hash=dedup_result.file_hash,
                    original_queue_id=dedup_result.original_queue_id,
                )

        logger.info(
            f"[{trace_id}] Step 3/7: Dedup passed — "
            f"{len(files)} files checked"
        )

        # Generate identifiers
        # data_uuid: always generated (even single file) — per-request group
        data_uuid = str(uuid7())
        filenames = [name for name, _ in files]
        total_size = sum(len(data) for _, data in files)

        # ── Step 4: COMMIT POINT — Write blobs (one per file) ─────────────
        blob_uuids: List[str] = []
        blob_paths: List[str] = []

        # Extract SDK canonical display IDs from metadata (if present)
        file_display_ids = (metadata or {}).get("file_display_ids", [])
        batch_display_id = (metadata or {}).get("batch_display_id", "")

        for i, (filename, file_data) in enumerate(files):
            blob_uuid = str(uuid7())
            blob_uuids.append(blob_uuid)

            # Enrich per-file metadata with canonical display IDs
            per_file_metadata = dict(metadata) if metadata else {}
            # Remove the array — each file gets its own display_id
            per_file_metadata.pop("file_display_ids", None)
            if i < len(file_display_ids):
                per_file_metadata["file_display_id"] = file_display_ids[i]
            if batch_display_id:
                per_file_metadata["batch_display_id"] = batch_display_id
            # source_document_id = Relay's data_uuid (per-request tracking)
            per_file_metadata["source_document_id"] = data_uuid

            try:
                blob_result = await self._heartbeat.write_blob(
                    blob_uuid=blob_uuid,
                    filename=filename,
                    file_data=file_data,
                    metadata=per_file_metadata,
                    jwt_token=jwt_token,
                )
            except JWTRejectedError:
                # Let JWT rejection propagate cleanly as 401
                raise
            except Exception as e:
                raise InternalError(
                    message=f"Blob write failed for {filename}: {e}",
                    original_error=e,
                ) from e

            blob_paths.append(blob_result.get("blob_path", ""))
            logger.debug(
                f"[{trace_id}] Step 4/7: Blob {i+1}/{len(files)} written — "
                f"uuid={blob_uuid}, file={filename}"
            )

        logger.info(
            f"[{trace_id}] Step 4/7: All blobs written — "
            f"{len(files)} files, data_uuid={data_uuid}"
        )

        # Record dedup hashes after successful commit
        # Level 1: Session cache (in-memory, per-request)
        for file_hash in per_file_hashes:
            dedup.record(file_hash)

        # Level 2: HeartBeat persistent record (across requests)
        for file_hash in per_file_hashes:
            try:
                await self._heartbeat.record_duplicate(
                    file_hash=file_hash,
                    queue_id=data_uuid,
                )
            except Exception as e:
                # Graceful degradation: if HeartBeat record fails,
                # session cache still catches within-batch duplicates
                logger.warning(
                    f"[{trace_id}] HeartBeat dedup record failed "
                    f"(hash={file_hash[:12]}...): {e}"
                )

        # ── Step 5: Enqueue Core (best-effort) ────────────────────────────
        queue_id = await self._enqueue_core(
            data_uuid, filenames, total_size, trace_id,
            metadata=metadata, jwt_token=jwt_token,
        )
        logger.info(
            f"[{trace_id}] Step 5/7: Core enqueued — queue_id={queue_id}"
        )

        # ── Step 6: Register blobs (fire-and-forget) ──────────────────────
        for i, (filename, file_data) in enumerate(files):
            await self._register_blob(
                blob_uuids[i], filename, len(file_data),
                per_file_hashes[i], api_key, trace_id,
                data_uuid=data_uuid,
                file_index=i,
                metadata=metadata, jwt_token=jwt_token,
            )
        logger.info(f"[{trace_id}] Step 6/7: Blobs registered")

        # ── Step 7: Audit log (fire-and-forget) ───────────────────────────
        await self._audit_log(
            data_uuid, queue_id, filenames, api_key, trace_id,
            metadata=metadata,
        )
        logger.info(f"[{trace_id}] Step 7/7: Audit logged")

        return IngestResult(
            data_uuid=data_uuid,
            queue_id=queue_id,
            filenames=filenames,
            file_count=len(files),
            total_size_bytes=total_size,
            file_hashes=per_file_hashes,
            blob_uuids=blob_uuids,
            blob_paths=blob_paths,
        )

    # ── Internal Helpers ──────────────────────────────────────────────────

    async def _check_daily_limit(
        self, api_key: str, file_count: int, trace_id: str
    ) -> None:
        """
        Step 2: Check daily upload limit.

        Priority: Redis (primary) -> HeartBeat (fallback) -> allow (degraded).
        """
        # Primary: Redis rate limiting
        if self._redis is not None and self._redis.is_available:
            try:
                result = await self._redis.check_rate_limit(
                    company_id=api_key,
                    file_count=file_count,
                )
                if not result.allowed:
                    raise RateLimitExceededError(
                        message=(
                            f"Daily upload limit reached. "
                            f"Limit: {result.limit}, remaining: {result.remaining}."
                        )
                    )
                return  # Redis check passed
            except RateLimitExceededError:
                raise
            except Exception as e:
                logger.warning(
                    f"[{trace_id}] Redis rate limit failed — falling back to HeartBeat: {e}"
                )

        # Fallback: HeartBeat
        try:
            result = await self._heartbeat.check_daily_limit(
                company_id=api_key,
                file_count=file_count,
            )
            if result.get("limit_reached"):
                remaining = result.get("remaining", 0)
                daily_limit = result.get("daily_limit", 0)
                raise RateLimitExceededError(
                    message=(
                        f"Daily upload limit reached. "
                        f"Limit: {daily_limit}, remaining: {remaining}."
                    )
                )
        except RateLimitExceededError:
            raise
        except Exception as e:
            # Graceful degradation: if both Redis and HeartBeat are down, allow
            logger.warning(
                f"[{trace_id}] Daily limit check failed — allowing: {e}"
            )

    async def _enqueue_core(
        self,
        data_uuid: str,
        filenames: List[str],
        file_size_bytes: int,
        trace_id: str,
        metadata: Optional[Dict] = None,
        jwt_token: Optional[str] = None,
    ) -> str:
        """Step 5: Enqueue file for Core processing (best-effort).

        Forwards JWT so Core can identify the user. Metadata is included
        for Core's own traceability records.
        """
        try:
            result = await self._core.enqueue(
                blob_uuid=data_uuid,
                filename=filenames[0] if len(filenames) == 1 else ",".join(filenames),
                file_size_bytes=file_size_bytes,
                batch_id=trace_id,
                metadata=metadata,
                jwt_token=jwt_token,
            )
            return result["queue_id"]
        except Exception as e:
            # Best-effort: orphaned blob will be reconciled by HeartBeat
            logger.warning(
                f"[{trace_id}] Core enqueue failed — blob is orphaned: {e}"
            )
            return f"orphan_{data_uuid}"

    async def _register_blob(
        self,
        blob_uuid: str,
        filename: str,
        file_size_bytes: int,
        file_hash: str,
        api_key: str,
        trace_id: str,
        data_uuid: str = "",
        file_index: int = 0,
        metadata: Optional[Dict] = None,
        jwt_token: Optional[str] = None,
    ) -> None:
        """Step 6: Register blob metadata in HeartBeat (fire-and-forget).

        Forwards metadata so HeartBeat stamps file_entries with identity/trace.
        Enriches metadata with per-file file_display_id and batch-level
        batch_display_id + source_document_id for canonical dual identity.
        JWT allows HeartBeat to verify the user identity.
        """
        # Enrich metadata with canonical display IDs
        enriched_metadata = dict(metadata) if metadata else {}

        # Map SDK's per-file display IDs (sent as array in metadata)
        file_display_ids = enriched_metadata.pop("file_display_ids", [])
        if file_index < len(file_display_ids):
            enriched_metadata["file_display_id"] = file_display_ids[file_index]

        # source_document_id = Relay's data_uuid (per-request tracking ID)
        if data_uuid:
            enriched_metadata["source_document_id"] = data_uuid

        try:
            await self._heartbeat.register_blob(
                blob_uuid=blob_uuid,
                filename=filename,
                file_size_bytes=file_size_bytes,
                file_hash=file_hash,
                api_key=api_key,
                metadata=enriched_metadata,
                jwt_token=jwt_token,
            )
        except Exception as e:
            logger.warning(
                f"[{trace_id}] Blob registration failed (non-critical): {e}"
            )

    async def _audit_log(
        self,
        data_uuid: str,
        queue_id: str,
        filenames: List[str],
        api_key: str,
        trace_id: str,
        metadata: Optional[Dict] = None,
    ) -> None:
        """Step 7: Log audit event (fire-and-forget).

        Includes SDK metadata for audit trail (user_trace_id, machine_guid, etc.).
        """
        audit_details: Dict[str, Any] = {
            "data_uuid": data_uuid,
            "queue_id": queue_id,
            "filenames": filenames,
            "trace_id": trace_id,
        }
        # Merge SDK identity/trace into audit details
        if metadata:
            audit_details["sdk_metadata"] = metadata

        try:
            await self._heartbeat.audit_log(
                service="relay-api",
                event_type="file.ingested",
                user_id=metadata.get("helium_user_id", api_key) if metadata else api_key,
                details=audit_details,
            )
        except Exception as e:
            logger.warning(
                f"[{trace_id}] Audit log failed (non-critical): {e}"
            )
